// biome-ignore-all lint/suspicious/noTemplateCurlyInString: the fixtures are JS source under test.
import { describe, expect, it } from 'vitest';
import { analyze, createSemantic } from '../../src/analysis/semantic.ts';
import { parse } from '../../src/ast.ts';
import { eliminateDeadCode } from '../../src/passes/dce/compressor.ts';
import { rolldownDceOptions } from '../../src/passes/dce/options.ts';
import { printModule } from '../../src/print/print-js.ts';
import { createPrinter, finishPrinter } from '../../src/print/printer.ts';

// Ported from oxc_minifier/tests/peephole/fold_constants.rs (`fold(x, y)` wraps both in `NOOP(...)`)
// and the fold, optional-chain, template and IIFE cases of dead_code_elimination.rs. oxc's
// fold_constants tests run full minify, so each expected output here is what real rolldown's
// tree-shake-only pass (`minify: false`) produces for that input; the dead_code_elimination.rs
// expectations are oxc's own.

type Case = [oxcTest: string, input: string, expected: string];

const normalize = (code: string): string =>
    code
        .split('\n')
        .map((line) => line.trim())
        .filter((line) => line !== '')
        .join(' ');

function eliminate(source: string): string {
    const { program } = parse(source, { ts: false, jsx: false, kind: 'module' });
    const semantic = createSemantic();
    analyze(semantic, program, true);
    eliminateDeadCode(program, semantic, rolldownDceOptions(), 'module', new Set(), true);
    const printer = createPrinter({ minify: false });
    printModule(printer, program);
    return normalize(finishPrinter(printer));
}

function runCases(cases: Case[]): void {
    const groups = new Map<string, Case[]>();
    for (const testCase of cases) {
        const group = groups.get(testCase[0]);
        if (group === undefined) groups.set(testCase[0], [testCase]);
        else group.push(testCase);
    }
    for (const [oxcTest, group] of groups) {
        describe(oxcTest, () => {
            it.each(group.map(([, input, expected]) => [input, expected]))('%s', (input, expected) => {
                expect(eliminate(input)).toBe(expected);
            });
        });
    }
}

const FOLD_CONSTANTS: Case[] = [
    ['test_comparison', 'NOOP((1, 2) !== 2)', 'NOOP(false);'],
    ['test_comparison', 'NOOP(({} <= {}))', 'NOOP({} <= {});'],
    ['test_comparison', 'NOOP(({} >= {}))', 'NOOP({} >= {});'],
    ['test_comparison', 'NOOP(({} > {}))', 'NOOP({} > {});'],
    ['test_comparison', 'NOOP(({} < {}))', 'NOOP({} < {});'],
    ['test_comparison', 'NOOP(([] <= []))', 'NOOP([] <= []);'],
    ['test_comparison', 'NOOP(([] >= []))', 'NOOP([] >= []);'],
    ['test_comparison', 'NOOP(([] > []))', 'NOOP([] > []);'],
    ['test_comparison', 'NOOP(([] < []))', 'NOOP([] < []);'],
    ['undefined_comparison1', 'NOOP(undefined == undefined)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(undefined == null)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(undefined == void 0)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(undefined == 0)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined == 1)', 'NOOP(false);'],
    ['undefined_comparison1', "NOOP(undefined == 'hi')", 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined == true)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined == false)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined === undefined)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(undefined === null)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined === void 0)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(undefined == x)', 'NOOP(void 0 == x);'],
    ['undefined_comparison1', 'NOOP(undefined != undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined != null)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined != void 0)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined != 0)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(undefined != 1)', 'NOOP(true);'],
    ['undefined_comparison1', "NOOP(undefined != 'hi')", 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(undefined != true)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(undefined != false)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(undefined !== undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined !== void 0)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined !== null)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(undefined != x)', 'NOOP(void 0 != x);'],
    ['undefined_comparison1', 'NOOP(undefined < undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined > undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined >= undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined <= undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(0 < undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(true > undefined)', 'NOOP(false);'],
    ['undefined_comparison1', "NOOP('hi' >= undefined)", 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(null <= undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined < 0)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined > true)', 'NOOP(false);'],
    ['undefined_comparison1', "NOOP(undefined >= 'hi')", 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined <= null)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(null == undefined)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(0 == undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(1 == undefined)', 'NOOP(false);'],
    ['undefined_comparison1', "NOOP('hi' == undefined)", 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(true == undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(false == undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(null === undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(void 0 === undefined)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(undefined == NaN)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(NaN == undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined == Infinity)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(Infinity == undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined == -Infinity)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(-Infinity == undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(({}) == undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined == ({}))', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(([]) == undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined == ([]))', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP((/a/g) == undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined == (/a/g))', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP((function(){}) == undefined)', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined == (function(){}))', 'NOOP(false);'],
    ['undefined_comparison1', 'NOOP(undefined != NaN)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(NaN != undefined)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(undefined != Infinity)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(Infinity != undefined)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(undefined != -Infinity)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(-Infinity != undefined)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(({}) != undefined)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(undefined != ({}))', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(([]) != undefined)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(undefined != ([]))', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP((/a/g) != undefined)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(undefined != (/a/g))', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP((function(){}) != undefined)', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(undefined != (function(){}))', 'NOOP(true);'],
    ['undefined_comparison1', 'NOOP(x == undefined)', 'NOOP(x == void 0);'],
    ['test_undefined_comparison2', 'NOOP("123" !== void 0)', 'NOOP(true);'],
    ['test_undefined_comparison2', 'NOOP("123" === void 0)', 'NOOP(false);'],
    ['test_undefined_comparison2', 'NOOP(void 0 !== "123")', 'NOOP(true);'],
    ['test_undefined_comparison2', 'NOOP(void 0 === "123")', 'NOOP(false);'],
    ['test_undefined_comparison3', 'NOOP("123" !== undefined)', 'NOOP(true);'],
    ['test_undefined_comparison3', 'NOOP("123" === undefined)', 'NOOP(false);'],
    ['test_undefined_comparison3', 'NOOP(undefined !== "123")', 'NOOP(true);'],
    ['test_undefined_comparison3', 'NOOP(undefined === "123")', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null == undefined)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null == null)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null == void 0)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null == 0)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null == 1)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null == 0n)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null == 1n)', 'NOOP(false);'],
    ['test_null_comparison1', "NOOP(null == 'hi')", 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null == true)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null == false)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null === undefined)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null === null)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null === void 0)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(x===null)', 'NOOP(x === null);'],
    ['test_null_comparison1', 'NOOP(x==null)', 'NOOP(x == null);'],
    ['test_null_comparison1', 'NOOP(null != undefined)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null != null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null != void 0)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null != 0)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null != 1)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null != 0n)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null != 1n)', 'NOOP(true);'],
    ['test_null_comparison1', "NOOP(null != 'hi')", 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null != true)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null != false)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null !== undefined)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null !== void 0)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null !== null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(x!=null)', 'NOOP(x != null);'],
    ['test_null_comparison1', 'NOOP(null < null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null > null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null >= null)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null <= null)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(0 < null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(0 > null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(0 >= null)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(0n < null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(0n > null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(0n >= null)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(true > null)', 'NOOP(true);'],
    ['test_null_comparison1', "NOOP('hi' < null)", 'NOOP(false);'],
    ['test_null_comparison1', "NOOP('hi' >= null)", 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null <= null)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null < 0)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null < 0n)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null > true)', 'NOOP(false);'],
    ['test_null_comparison1', "NOOP(null < 'hi')", 'NOOP(false);'],
    ['test_null_comparison1', "NOOP(null >= 'hi')", 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null <= null)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null == null)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(0 == null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(1 == null)', 'NOOP(false);'],
    ['test_null_comparison1', "NOOP('hi' == null)", 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(true == null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(false == null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null === null)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(void 0 === null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null == NaN)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(NaN == null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null == Infinity)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(Infinity == null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null == -Infinity)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(-Infinity == null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(({}) == null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null == ({}))', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(([]) == null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null == ([]))', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP((/a/g) == null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null == (/a/g))', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP((function(){}) == null)', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null == (function(){}))', 'NOOP(false);'],
    ['test_null_comparison1', 'NOOP(null != NaN)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(NaN != null)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null != Infinity)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(Infinity != null)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null != -Infinity)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(-Infinity != null)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(({}) != null)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null != ({}))', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(([]) != null)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null != ([]))', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP((/a/g) != null)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null != (/a/g))', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP((function(){}) != null)', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(null != (function(){}))', 'NOOP(true);'],
    ['test_null_comparison1', 'NOOP(({a:f()})==null)', 'NOOP({ a: f() } == null);'],
    ['test_null_comparison1', 'NOOP([f()]==null)', 'NOOP([f()] == null);'],
    ['test_null_comparison1', 'NOOP(x==null)', 'NOOP(x == null);'],
    ['test_boolean_boolean_comparison', 'NOOP(!x == !y)', 'NOOP(!x == !y);'],
    ['test_boolean_boolean_comparison', 'NOOP(!x < !y)', 'NOOP(!x < !y);'],
    ['test_boolean_boolean_comparison', 'NOOP(!x!==!y)', 'NOOP(!x !== !y);'],
    ['test_boolean_boolean_comparison', 'NOOP(!x == !x)', 'NOOP(!x == !x);'],
    ['test_boolean_boolean_comparison', 'NOOP(!x <! x)', 'NOOP(!x < !x);'],
    ['test_boolean_boolean_comparison', 'NOOP(!x !== !x)', 'NOOP(!x !== !x);'],
    ['test_boolean_number_comparison', 'NOOP(!x==+y)', 'NOOP(!x == +y);'],
    ['test_boolean_number_comparison', 'NOOP(!x<=+y)', 'NOOP(!x <= +y);'],
    ['test_boolean_number_comparison', 'NOOP(!x !== +y)', 'NOOP(!x !== +y);'],
    ['test_number_boolean_comparison', 'NOOP(+x==!y)', 'NOOP(+x == !y);'],
    ['test_number_boolean_comparison', 'NOOP(+x<=!y)', 'NOOP(+x <= !y);'],
    ['test_number_boolean_comparison', 'NOOP(+x === !y)', 'NOOP(+x === !y);'],
    ['test_boolean_string_comparison', "NOOP(!x==''+y)", 'NOOP(!x == "" + y);'],
    ['test_boolean_string_comparison', "NOOP(!x<=''+y)", 'NOOP(!x <= "" + y);'],
    ['test_boolean_string_comparison', "NOOP(!x !== '' + y)", 'NOOP(!x !== "" + y);'],
    ['test_string_boolean_comparison', "NOOP(''+x==!y)", 'NOOP("" + x == !y);'],
    ['test_string_boolean_comparison', "NOOP(''+x<=!y)", 'NOOP("" + x <= !y);'],
    ['test_string_boolean_comparison', "NOOP('' + x === !y)", 'NOOP("" + x === !y);'],
    ['test_number_number_comparison', 'NOOP(1 > 1)', 'NOOP(false);'],
    ['test_number_number_comparison', 'NOOP(2 == 3)', 'NOOP(false);'],
    ['test_number_number_comparison', 'NOOP(3.6 === 3.6)', 'NOOP(true);'],
    ['test_number_number_comparison', 'NOOP(+x > +y)', 'NOOP(+x > +y);'],
    ['test_number_number_comparison', 'NOOP(+x == +y)', 'NOOP(+x == +y);'],
    ['test_number_number_comparison', 'NOOP(+x === +y)', 'NOOP(+x === +y);'],
    ['test_number_number_comparison', 'NOOP(+x > +x)', 'NOOP(+x > +x);'],
    ['test_number_number_comparison', 'NOOP(+x == +x)', 'NOOP(+x == +x);'],
    ['test_number_number_comparison', 'NOOP(+x === +x)', 'NOOP(+x === +x);'],
    ['test_string_string_comparison', "NOOP('a' < 'b')", 'NOOP(true);'],
    ['test_string_string_comparison', "NOOP('a' <= 'b')", 'NOOP(true);'],
    ['test_string_string_comparison', "NOOP('a' > 'b')", 'NOOP(false);'],
    ['test_string_string_comparison', "NOOP('a' >= 'b')", 'NOOP(false);'],
    ['test_string_string_comparison', "NOOP(+'a' < +'b')", 'NOOP(false);'],
    ['test_string_string_comparison', "NOOP(typeof a < 'a')", 'NOOP(typeof a < "a");'],
    ['test_string_string_comparison', "NOOP('a' >= typeof a)", 'NOOP("a" >= typeof a);'],
    ['test_string_string_comparison', 'NOOP(typeof a < typeof a)', 'NOOP(typeof a < typeof a);'],
    ['test_string_string_comparison', 'NOOP(typeof a >= typeof a)', 'NOOP(typeof a >= typeof a);'],
    ['test_string_string_comparison', 'NOOP(typeof 3 > typeof 4)', 'NOOP(false);'],
    ['test_string_string_comparison', 'NOOP(typeof function() {} < typeof function() {})', 'NOOP(false);'],
    ['test_string_string_comparison', "NOOP('a' == 'a')", 'NOOP(true);'],
    ['test_string_string_comparison', "NOOP('b' != 'a')", 'NOOP(true);'],
    ['test_string_string_comparison', "NOOP(typeof a != 'number')", 'NOOP(typeof a != "number");'],
    ['test_string_string_comparison', "NOOP(typeof a != 'unknown')", 'NOOP(typeof a != "unknown");'],
    ['test_string_string_comparison', "NOOP('a' === 'a')", 'NOOP(true);'],
    ['test_string_string_comparison', "NOOP('b' !== 'a')", 'NOOP(true);'],
    ['test_string_string_comparison', "NOOP('' + x <= '' + y)", 'NOOP("" + x <= "" + y);'],
    ['test_string_string_comparison', "NOOP('' + x != '' + y)", 'NOOP("" + x != "" + y);'],
    ['test_string_string_comparison', "NOOP('' + x === '' + y)", 'NOOP("" + x === "" + y);'],
    ['test_string_string_comparison', "NOOP('' + x <= '' + x)", 'NOOP("" + x <= "" + x);'],
    ['test_string_string_comparison', "NOOP('' + x != '' + x)", 'NOOP("" + x != "" + x);'],
    ['test_string_string_comparison', "NOOP('' + x === '' + x)", 'NOOP("" + x === "" + x);'],
    ['test_string_string_comparison', 'if ("\u000bstr\u000bing\u000b" !== "\\u000Bstr\\u000Bing\\u000B") {}', ''],
    ['test_number_string_comparison', "NOOP(1 < '2')", 'NOOP(true);'],
    ['test_number_string_comparison', "NOOP(2 > '1')", 'NOOP(true);'],
    ['test_number_string_comparison', "NOOP(123 > '34')", 'NOOP(true);'],
    ['test_number_string_comparison', "NOOP(NaN >= 'NaN')", 'NOOP(false);'],
    ['test_number_string_comparison', "NOOP(1 == '2')", 'NOOP(false);'],
    ['test_number_string_comparison', "NOOP(1 != '1')", 'NOOP(false);'],
    ['test_number_string_comparison', "NOOP(NaN == 'NaN')", 'NOOP(false);'],
    ['test_number_string_comparison', "NOOP(1 === '1')", 'NOOP(false);'],
    ['test_number_string_comparison', "NOOP(1 !== '1')", 'NOOP(true);'],
    ['test_number_string_comparison', "NOOP(+x>''+y)", 'NOOP(+x > "" + y);'],
    ['test_number_string_comparison', "NOOP(+x==''+y)", 'NOOP(+x == "" + y);'],
    ['test_number_string_comparison', "NOOP(+x !== '' + y)", 'NOOP(+x !== "" + y);'],
    ['test_string_number_comparison', "NOOP('1' < 2)", 'NOOP(true);'],
    ['test_string_number_comparison', "NOOP('2' > 1)", 'NOOP(true);'],
    ['test_string_number_comparison', "NOOP('123' > 34)", 'NOOP(true);'],
    ['test_string_number_comparison', "NOOP('NaN' < NaN)", 'NOOP(false);'],
    ['test_string_number_comparison', "NOOP('1' == 2)", 'NOOP(false);'],
    ['test_string_number_comparison', "NOOP('1' != 1)", 'NOOP(false);'],
    ['test_string_number_comparison', "NOOP('NaN' == NaN)", 'NOOP(false);'],
    ['test_string_number_comparison', "NOOP('1' === 1)", 'NOOP(false);'],
    ['test_string_number_comparison', "NOOP('1' !== 1)", 'NOOP(true);'],
    ['test_string_number_comparison', "NOOP(''+x<+y)", 'NOOP("" + x < +y);'],
    ['test_string_number_comparison', "NOOP(''+x==+y)", 'NOOP("" + x == +y);'],
    ['test_string_number_comparison', "NOOP('' + x === +y)", 'NOOP("" + x === +y);'],
    ['test_nan_comparison', 'NOOP(NaN < 1)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(NaN <= 1)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(NaN > 1)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(NaN >= 1)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(NaN < 1n)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(NaN <= 1n)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(NaN > 1n)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(NaN >= 1n)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(NaN < NaN)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(NaN >= NaN)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(NaN == NaN)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(NaN === NaN)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(NaN < null)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(null >= NaN)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(NaN == null)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(null != NaN)', 'NOOP(true);'],
    ['test_nan_comparison', 'NOOP(null === NaN)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(NaN < undefined)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(undefined >= NaN)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(NaN == undefined)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(undefined != NaN)', 'NOOP(true);'],
    ['test_nan_comparison', 'NOOP(undefined === NaN)', 'NOOP(false);'],
    ['test_nan_comparison', 'NOOP(NaN<x)', 'NOOP(NaN < x);'],
    ['test_nan_comparison', 'NOOP(x>=NaN)', 'NOOP(x >= NaN);'],
    ['test_nan_comparison', 'NOOP(NaN==x)', 'NOOP(NaN == x);'],
    ['test_nan_comparison', 'NOOP(x!=NaN)', 'NOOP(x != NaN);'],
    ['test_nan_comparison', 'NOOP(NaN === x)', 'NOOP(NaN === x);'],
    ['test_nan_comparison', 'NOOP(x !== NaN)', 'NOOP(x !== NaN);'],
    ['test_nan_comparison', 'NOOP(NaN==foo())', 'NOOP(NaN == foo());'],
    ['test_object_comparison1', 'NOOP(!new Date())', 'NOOP(false);'],
    ['test_object_comparison1', 'NOOP(!!new Date())', 'NOOP(true);'],
    ['test_object_comparison1', 'NOOP(!new Date(foo))', 'NOOP(!new Date(foo));'],
    ['test_object_comparison1', 'NOOP(new Date() == null)', 'NOOP(false);'],
    ['test_object_comparison1', 'NOOP(new Date() == undefined)', 'NOOP(false);'],
    ['test_object_comparison1', 'NOOP(new Date() != null)', 'NOOP(true);'],
    ['test_object_comparison1', 'NOOP(new Date() != undefined)', 'NOOP(true);'],
    ['test_object_comparison1', 'NOOP(null == new Date())', 'NOOP(false);'],
    ['test_object_comparison1', 'NOOP(undefined == new Date())', 'NOOP(false);'],
    ['test_object_comparison1', 'NOOP(null != new Date())', 'NOOP(true);'],
    ['test_object_comparison1', 'NOOP(undefined != new Date())', 'NOOP(true);'],
    ['test_object_comparison1', 'NOOP(new Date(foo) != undefined)', 'NOOP(new Date(foo) != void 0);'],
    ['js_typeof', 'NOOP(x = typeof 1n)', 'NOOP(x = "bigint");'],
    ['js_typeof', 'NOOP(x = typeof 1)', 'NOOP(x = "number");'],
    ['js_typeof', "NOOP(x = typeof 'foo')", 'NOOP(x = "string");'],
    ['js_typeof', 'NOOP(x = typeof true)', 'NOOP(x = "boolean");'],
    ['js_typeof', 'NOOP(x = typeof false)', 'NOOP(x = "boolean");'],
    ['js_typeof', 'NOOP(x = typeof null)', 'NOOP(x = "object");'],
    ['js_typeof', 'NOOP(x = typeof undefined)', 'NOOP(x = "undefined");'],
    ['js_typeof', 'NOOP(x = typeof void 0)', 'NOOP(x = "undefined");'],
    ['js_typeof', 'NOOP(x = typeof [])', 'NOOP(x = "object");'],
    ['js_typeof', 'NOOP(x = typeof [1])', 'NOOP(x = "object");'],
    ['js_typeof', 'NOOP(x = typeof [1,[]])', 'NOOP(x = "object");'],
    ['js_typeof', 'NOOP(x = typeof {})', 'NOOP(x = "object");'],
    ['js_typeof', 'var a, b; NOOP(x = typeof (a === b))', 'NOOP(x = "boolean");'],
    ['js_typeof', 'var foo; NOOP(x = typeof { foo })', 'NOOP(x = "object");'],
    ['js_typeof', 'NOOP(x = typeof function() {})', 'NOOP(x = "function");'],
    ['js_typeof', 'NOOP(x = typeof (() => {}))', 'NOOP(x = "function");'],
    ['js_typeof', 'NOOP(x = typeof class{})', 'NOOP(x = "function");'],
    ['js_typeof', 'NOOP(x = typeof foo)', 'NOOP(x = typeof foo);'],
    ['js_typeof', 'NOOP(x = typeof[1,[foo()]])', 'NOOP(x = typeof [1, [foo()]]);'],
    ['js_typeof', 'NOOP(x = typeof{bathwater:baby()})', 'NOOP(x = typeof { bathwater: baby() });'],
    ['js_typeof', 'NOOP(x = typeof class { static { foo() } })', 'NOOP(x = typeof class { static { foo(); } });'],
    ['test_fold_unary', 'NOOP(!foo())', 'NOOP(!foo());'],
    ['test_fold_unary', 'NOOP(~foo())', 'NOOP(~foo());'],
    ['test_fold_unary', 'NOOP(-foo())', 'NOOP(-foo());'],
    ['test_fold_unary', 'NOOP(a=!true)', 'NOOP(a = false);'],
    ['test_fold_unary', 'NOOP(a=!10)', 'NOOP(a = false);'],
    ['test_fold_unary', 'NOOP(a=!false)', 'NOOP(a = true);'],
    ['test_fold_unary', 'NOOP(a=!foo())', 'NOOP(a = !foo());'],
    ['test_fold_unary', 'NOOP(a = !!void b)', 'NOOP(a = !!void b);'],
    ['test_fold_unary', 'NOOP(a=-0)', 'NOOP(a = -0);'],
    ['test_fold_unary', 'NOOP(a=-(0))', 'NOOP(a = -0);'],
    ['test_fold_unary', 'NOOP(a=-Infinity)', 'NOOP(a = -Infinity);'],
    ['test_fold_unary', 'NOOP(a=-NaN)', 'NOOP(a = NaN);'],
    ['test_fold_unary', 'NOOP(a=-foo())', 'NOOP(a = -foo());'],
    ['test_fold_unary', 'NOOP(-undefined)', 'NOOP(NaN);'],
    ['test_fold_unary', 'NOOP(-null)', 'NOOP(-0);'],
    ['test_fold_unary', 'NOOP(-NaN)', 'NOOP(NaN);'],
    ['test_fold_unary', 'NOOP(a=+true)', 'NOOP(a = 1);'],
    ['test_fold_unary', 'NOOP(a=+10)', 'NOOP(a = 10);'],
    ['test_fold_unary', 'NOOP(a=+false)', 'NOOP(a = 0);'],
    ['test_fold_unary', 'NOOP(a=+foo())', 'NOOP(a = +foo());'],
    ['test_fold_unary', 'NOOP(a=+f)', 'NOOP(a = +f);'],
    ['test_fold_unary', 'NOOP(a=+(f?true:false))', 'NOOP(a = +(f ? true : false));'],
    ['test_fold_unary', 'NOOP(a=+(f?!0:!1))', 'NOOP(a = +(f ? !0 : !1));'],
    ['test_fold_unary', 'NOOP(a=+(f?(foo, !0):(bar, !1)))', 'NOOP(a = +(f ? (foo, !0) : (bar, !1)));'],
    ['test_fold_unary', 'NOOP(a=+0)', 'NOOP(a = 0);'],
    ['test_fold_unary', 'NOOP(a=+Infinity)', 'NOOP(a = Infinity);'],
    ['test_fold_unary', 'NOOP(a=+NaN)', 'NOOP(a = NaN);'],
    ['test_fold_unary', 'NOOP(a=+-7)', 'NOOP(a = -7);'],
    ['test_fold_unary', 'NOOP(a=+.5)', 'NOOP(a = .5);'],
    ['test_fold_unary', 'NOOP(a=~~0)', 'NOOP(a = 0);'],
    ['test_fold_unary', 'NOOP(a=~~10)', 'NOOP(a = 10);'],
    ['test_fold_unary', 'NOOP(a=~-7)', 'NOOP(a = 6);'],
    ['test_fold_unary', 'NOOP(a=~~foo())', 'NOOP(a = ~~foo());'],
    ['test_fold_unary', 'NOOP(a=~0xffffffff)', 'NOOP(a = 0);'],
    ['test_fold_unary', 'NOOP(a=~~0xffffffff)', 'NOOP(a = -1);'],
    ['test_fold_unary', 'NOOP(a=~.5)', 'NOOP(a = -1);'],
    ['test_fold_unary', 'NOOP(a=+[])', 'NOOP(a = 0);'],
    ['test_fold_unary', 'NOOP(a=+[...foo])', 'NOOP(a = +[...foo]);'],
    ['test_fold_unary', 'NOOP(a=+[,])', 'NOOP(a = 0);'],
    ['test_fold_unary', 'NOOP(a=+[0])', 'NOOP(a = 0);'],
    ['test_fold_unary', "NOOP(a=+['0x10'])", 'NOOP(a = 16);'],
    ['test_fold_unary', 'NOOP(a=+[[]])', 'NOOP(a = 0);'],
    ['test_fold_unary', 'NOOP(a=+[0, 1])', 'NOOP(a = NaN);'],
    ['test_fold_unary', 'var foo; NOOP(a=+[0, ...foo])', 'var foo; NOOP(a = +[0, ...foo]);'],
    ['test_fold_unary', "var foo; NOOP(a=+[0, ...[foo ? 'foo': ''], 1])", 'NOOP(a = NaN);'],
    ['test_fold_unary', 'NOOP(a=+[false])', 'NOOP(a = NaN);'],
    ['test_fold_unary', 'NOOP(a=+[true])', 'NOOP(a = NaN);'],
    ['test_fold_unary', 'NOOP(a=+[undefined])', 'NOOP(a = 0);'],
    ['test_fold_unary', 'NOOP(a=+[null])', 'NOOP(a = 0);'],
    ['test_fold_unary_big_int', 'NOOP(-(1n))', 'NOOP(-1n);'],
    ['test_fold_unary_big_int', 'NOOP(- -1n)', 'NOOP(1n);'],
    ['test_fold_unary_big_int', 'NOOP(!1n)', 'NOOP(false);'],
    ['test_fold_unary_big_int', 'NOOP(~0n)', 'NOOP(-1n);'],
    ['test_fold_unary_big_int', 'NOOP(~-1n)', 'NOOP(0n);'],
    ['test_fold_unary_big_int', 'NOOP(~~1n)', 'NOOP(1n);'],
    ['test_fold_unary_big_int', 'NOOP(~0x3n)', 'NOOP(-4n);'],
    ['test_fold_unary_big_int', 'NOOP(~0b11n)', 'NOOP(-4n);'],
    ['test_unary_ops_string_compare', 'NOOP(a = -1)', 'NOOP(a = -1);'],
    ['test_unary_ops_string_compare', 'NOOP(a = ~0)', 'NOOP(a = -1);'],
    ['test_unary_ops_string_compare', 'NOOP(a = ~1)', 'NOOP(a = -2);'],
    ['test_unary_ops_string_compare', 'NOOP(a = ~101)', 'NOOP(a = -102);'],
    ['test_unary_ops_string_compare', 'NOOP(a = ~1.1)', 'NOOP(a = -2);'],
    ['test_unary_ops_string_compare', 'NOOP(a = ~0x3)', 'NOOP(a = -4);'],
    ['test_unary_ops_string_compare', 'NOOP(a = ~9)', 'NOOP(a = -10);'],
    ['test_unary_ops_string_compare', 'NOOP(a = ~b)', 'NOOP(a = ~b);'],
    ['test_unary_ops_string_compare', 'NOOP(a = ~NaN)', 'NOOP(a = -1);'],
    ['test_unary_ops_string_compare', 'NOOP(a = ~-Infinity)', 'NOOP(a = -1);'],
    ['test_unary_ops_string_compare', 'NOOP(x = ~2147483658.0)', 'NOOP(x = 2147483637);'],
    ['test_unary_ops_string_compare', 'NOOP(x = ~-2147483658)', 'NOOP(x = -2147483639);'],
    ['test_fold_logical_op', 'NOOP(x = true && x)', 'NOOP(x = x);'],
    ['test_fold_logical_op', 'NOOP(x = [foo()] && x)', 'NOOP(x = (foo(), x));'],
    ['test_fold_logical_op', 'NOOP(x = false && x)', 'NOOP(x = false);'],
    ['test_fold_logical_op', 'NOOP(x = true || x)', 'NOOP(x = true);'],
    ['test_fold_logical_op', 'NOOP(x = false || x)', 'NOOP(x = x);'],
    ['test_fold_logical_op', 'NOOP(x = 0 && x)', 'NOOP(x = 0);'],
    ['test_fold_logical_op', 'NOOP(x = 3 || x)', 'NOOP(x = 3);'],
    ['test_fold_logical_op', 'NOOP(x = 0n && x)', 'NOOP(x = 0n);'],
    ['test_fold_logical_op', 'NOOP(x = 3n || x)', 'NOOP(x = 3n);'],
    ['test_fold_logical_op', 'NOOP(x = false || 0)', 'NOOP(x = 0);'],
    ['test_fold_logical_op', 'NOOP(a = x && true)', 'NOOP(a = x && true);'],
    ['test_fold_logical_op', 'NOOP(a = x && false)', 'NOOP(a = x && false);'],
    ['test_fold_logical_op', 'NOOP(a = x || 3)', 'NOOP(a = x || 3);'],
    ['test_fold_logical_op', 'NOOP(a = x || false)', 'NOOP(a = x || false);'],
    ['test_fold_logical_op', 'NOOP(a = b ? c : x || false)', 'NOOP(a = b ? c : x || false);'],
    ['test_fold_logical_op', 'NOOP(a = b ? x || false : c)', 'NOOP(a = b ? x || false : c);'],
    ['test_fold_logical_op', 'NOOP(a = b ? c : x && true)', 'NOOP(a = b ? c : x && true);'],
    ['test_fold_logical_op', 'NOOP(a = b ? x && true : c)', 'NOOP(a = b ? x && true : c);'],
    ['test_fold_logical_op', 'NOOP(a = x || false ? b : c)', 'NOOP(a = x || false ? b : c);'],
    ['test_fold_logical_op', 'NOOP(a = x && true ? b : c)', 'NOOP(a = x && true ? b : c);'],
    ['test_fold_logical_op', 'NOOP(x = foo() || true || bar())', 'NOOP(x = foo() || true);'],
    ['test_fold_logical_op', 'NOOP(x = foo() || true && bar())', 'NOOP(x = foo() || bar());'],
    ['test_fold_logical_op', 'NOOP(x = foo() || false && bar())', 'NOOP(x = foo() || false);'],
    ['test_fold_logical_op', 'NOOP(x = foo() && false && bar())', 'NOOP(x = foo() && false);'],
    ['test_fold_logical_op', 'NOOP(x = foo() && false || bar())', 'NOOP(x = (foo(), bar()));'],
    ['test_fold_logical_op', 'NOOP(x = foo() || false || bar())', 'NOOP(x = foo() || bar());'],
    ['test_fold_logical_op', 'NOOP(x = foo() && true && bar())', 'NOOP(x = foo() && bar());'],
    ['test_fold_logical_op', 'NOOP(x = foo() || true || bar())', 'NOOP(x = foo() || true);'],
    ['test_fold_logical_op', 'NOOP(x = foo() && false && bar())', 'NOOP(x = foo() && false);'],
    ['test_fold_logical_op', 'NOOP(x = foo() && 0 && bar())', 'NOOP(x = foo() && 0);'],
    ['test_fold_logical_op', 'NOOP(x = foo() && 1 && bar())', 'NOOP(x = foo() && bar());'],
    ['test_fold_logical_op', 'NOOP(x = foo() || 0 || bar())', 'NOOP(x = foo() || bar());'],
    ['test_fold_logical_op', 'NOOP(x = foo() || 1 || bar())', 'NOOP(x = foo() || 1);'],
    ['test_fold_logical_op', 'NOOP(x = foo() && 0n && bar())', 'NOOP(x = foo() && 0n);'],
    ['test_fold_logical_op', 'NOOP(x = foo() && 1n && bar())', 'NOOP(x = foo() && bar());'],
    ['test_fold_logical_op', 'NOOP(x = foo() || 0n || bar())', 'NOOP(x = foo() || bar());'],
    ['test_fold_logical_op', 'NOOP(x = foo() || 1n || bar())', 'NOOP(x = foo() || 1n);'],
    ['test_fold_logical_op', 'NOOP(x = foo() || bar() || baz())', 'NOOP(x = foo() || bar() || baz());'],
    ['test_fold_logical_op', 'NOOP(x = foo() && bar() && baz())', 'NOOP(x = foo() && bar() && baz());'],
    ['test_fold_logical_op', 'NOOP(0 || b())', 'NOOP(b());'],
    ['test_fold_logical_op', 'NOOP(1 && b())', 'NOOP(b());'],
    ['test_fold_logical_op', 'NOOP(a() && (1 && b()))', 'NOOP(a() && b());'],
    ['test_fold_logical_op', 'NOOP((a() && 1) && b())', 'NOOP(a() && b());'],
    ['test_fold_logical_op', "NOOP((x || '') || y)", 'NOOP(x || y);'],
    ['test_fold_logical_op', "NOOP(false || (x || ''))", 'NOOP(x || "");'],
    ['test_fold_logical_op', 'NOOP((x && 1) && y)', 'NOOP(x && y);'],
    ['test_fold_logical_op', 'NOOP(true && (x && 1))', 'NOOP(x && 1);'],
    ['test_fold_logical_op', 'NOOP(x = foo() && true || bar())', 'NOOP(x = foo() && true || bar());'],
    ['test_fold_logical_op', 'NOOP(foo() && true || bar())', 'NOOP(foo() && true || bar());'],
    ['test_fold_logical_op', 'var y; x = (true && y)()', 'var y; x = y();'],
    ['test_fold_logical_op', 'var y; x = (true && y.z)()', 'var y; x = (0, y.z)();'],
    ['test_fold_logical_op', 'var y; x = (false || y)()', 'var y; x = y();'],
    ['test_fold_logical_op', 'var y; x = (false || y.z)()', 'var y; x = (0, y.z)();'],
    ['test_fold_logical_op2', 'NOOP(x = function(){} && x)', 'NOOP(x = x);'],
    ['test_preserve_cjs_module_lexer_hint', 'NOOP(x = 0 && (module.exports ||= y))', 'NOOP(x = 0);'],
    ['test_preserve_cjs_module_lexer_hint', 'NOOP(x = 0 && foo())', 'NOOP(x = 0);'],
    ['test_fold_nullish_coalesce', 'NOOP(null ?? 1)', 'NOOP(1);'],
    ['test_fold_nullish_coalesce', 'NOOP(undefined ?? false)', 'NOOP(false);'],
    ['test_fold_nullish_coalesce', 'NOOP((a(), null) ?? 1)', 'NOOP((a(), 1));'],
    ['test_fold_nullish_coalesce', 'NOOP(x = [foo()] ?? x)', 'NOOP(x = [foo()]);'],
    ['test_fold_nullish_coalesce', 'NOOP(x = false ?? x)', 'NOOP(x = false);'],
    ['test_fold_nullish_coalesce', 'NOOP(x = true ?? x)', 'NOOP(x = true);'],
    ['test_fold_nullish_coalesce', 'NOOP(x = 0 ?? x)', 'NOOP(x = 0);'],
    ['test_fold_nullish_coalesce', 'NOOP(x = 3 ?? x)', 'NOOP(x = 3);'],
    ['test_fold_nullish_coalesce', 'NOOP(a = x ?? true)', 'NOOP(a = x ?? true);'],
    ['test_fold_nullish_coalesce', 'NOOP(a = x ?? false)', 'NOOP(a = x ?? false);'],
    ['test_fold_nullish_coalesce', 'NOOP(a = x ?? 3)', 'NOOP(a = x ?? 3);'],
    ['test_fold_nullish_coalesce', 'NOOP(a = b ? c : x ?? false)', 'NOOP(a = b ? c : x ?? false);'],
    ['test_fold_nullish_coalesce', 'NOOP(a = b ? x ?? false : c)', 'NOOP(a = b ? x ?? false : c);'],
    ['test_fold_nullish_coalesce', 'NOOP(a = x ?? false ? b : c)', 'NOOP(a = x ?? false ? b : c);'],
    ['test_fold_nullish_coalesce', 'NOOP(a = x ?? true ? b : c)', 'NOOP(a = x ?? true ? b : c);'],
    ['test_fold_nullish_coalesce', 'NOOP(x = foo() ?? true ?? bar())', 'NOOP(x = foo() ?? true ?? bar());'],
    ['test_fold_nullish_coalesce', 'NOOP(x = foo() ?? (true && bar()))', 'NOOP(x = foo() ?? bar());'],
    ['test_fold_nullish_coalesce', 'NOOP(x = (foo() || false) ?? bar())', 'NOOP(x = (foo() || false) ?? bar());'],
    ['test_fold_nullish_coalesce', 'NOOP(a() ?? (1 ?? b()))', 'NOOP(a() ?? 1);'],
    ['test_fold_nullish_coalesce', 'NOOP((a() ?? 1) ?? b())', 'NOOP(a() ?? 1 ?? b());'],
    ['test_fold_nullish_coalesce', 'var y; x = (y ?? 1)()', 'var y; x = (y ?? 1)();'],
    ['test_fold_nullish_coalesce', 'var y; x = (y.z ?? 1)()', 'var y; x = (y.z ?? 1)();'],
    ['test_fold_nullish_coalesce', 'var y; x = (null ?? y)()', 'var y; x = y();'],
    ['test_fold_nullish_coalesce', 'var y; x = (null ?? y.z)()', 'var y; x = (0, y.z)();'],
    ['test_fold_void', 'NOOP(void 0)', 'NOOP(void 0);'],
    ['test_fold_void', 'NOOP(void 1)', 'NOOP(void 0);'],
    ['test_fold_void', 'NOOP(void x)', 'NOOP(void x);'],
    ['test_fold_void', 'NOOP(void x())', 'NOOP(void x());'],
    ['test_fold_opt_chain', 'NOOP(a = x?.y)', 'NOOP(a = x?.y);'],
    ['test_fold_opt_chain', 'NOOP(a = x?.())', 'NOOP(a = x?.());'],
    ['test_fold_opt_chain', 'NOOP(x = foo() ?. (true && bar()))', 'NOOP(x = foo()?.(bar()));'],
    ['test_fold_opt_chain', 'NOOP(a() ?. (1 ?? b()))', 'NOOP(a()?.(1));'],
    ['test_fold_opt_chain', 'NOOP(x = undefined?.y)', 'NOOP(x = void 0);'],
    ['test_fold_opt_chain', 'NOOP(x = null?.y)', 'NOOP(x = void 0);'],
    ['test_fold_opt_chain', 'NOOP(x = undefined?.[foo])', 'NOOP(x = void 0);'],
    ['test_fold_opt_chain', 'NOOP(x = null?.[foo])', 'NOOP(x = void 0);'],
    ['test_fold_opt_chain', 'NOOP(x = undefined?.())', 'NOOP(x = void 0);'],
    ['test_fold_opt_chain', 'NOOP(x = null?.())', 'NOOP(x = void 0);'],
    ['test_fold_opt_chain', 'NOOP(x = (foo(), null)?.y)', 'NOOP(x = (foo(), void 0));'],
    ['test_fold_opt_chain', 'NOOP(x = (foo(), null)?.())', 'NOOP(x = (foo(), void 0));'],
    ['test_fold_opt_chain', 'NOOP(x = null?.foo.bar)', 'NOOP(x = void 0);'],
    ['test_fold_opt_chain', 'NOOP(x = ((null))?.foo)', 'NOOP(x = void 0);'],
    ['test_fold_opt_chain', 'NOOP(x = null?.foo())', 'NOOP(x = void 0);'],
    ['test_fold_opt_chain', 'NOOP(x = null?.foo.bar.baz())', 'NOOP(x = void 0);'],
    ['test_fold_opt_chain', 'NOOP(x = (foo(), null)?.bar.baz)', 'NOOP(x = (foo(), void 0));'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = ("")?.foo)', 'NOOP(x = "".foo);'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = (1)?.foo)', 'NOOP(x = 1 .foo);'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = (1n)?.foo)', 'NOOP(x = 1n.foo);'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = ({})?.foo)', 'NOOP(x = {}.foo);'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = ([])?.foo)', 'NOOP(x = [].foo);'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = (() => 0)?.foo)', 'NOOP(x = (() => 0).foo);'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = (class {})?.foo)', 'NOOP(x = class {}.foo);'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = /a/?.flags)', 'NOOP(x = /a/.flags);'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = ({})?.["foo"])', 'NOOP(x = {}["foo"]);'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = (() => 0)?.())', 'NOOP(x = (() => 0)());'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = (foo(), {})?.bar)', 'NOOP(x = (foo(), {}).bar);'],
    [
        'test_fold_opt_chain_non_nullish_base',
        'NOOP(x = Number?.POSITIVE_INFINITY?.foo)',
        'NOOP(x = Number?.POSITIVE_INFINITY?.foo);',
    ],
    [
        'test_fold_opt_chain_non_nullish_base',
        'NOOP(x = Number?.NEGATIVE_INFINITY?.foo)',
        'NOOP(x = Number?.NEGATIVE_INFINITY?.foo);',
    ],
    [
        'test_fold_opt_chain_non_nullish_base',
        'const Number = 1; x = Number?.POSITIVE_INFINITY?.foo',
        'x = 1 .POSITIVE_INFINITY?.foo;',
    ],
    [
        'test_fold_opt_chain_non_nullish_base',
        'const Number = 1; x = Number?.POSITIVE_INFINITY?.[foo()]',
        'x = 1 .POSITIVE_INFINITY?.[foo()];',
    ],
    [
        'test_fold_opt_chain_non_nullish_base',
        'const Number = 1; x = Number?.POSITIVE_INFINITY?.(foo())',
        'x = 1 .POSITIVE_INFINITY?.(foo());',
    ],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = b?.foo)', 'NOOP(x = b?.foo);'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = foo()?.bar)', 'NOOP(x = foo()?.bar);'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = []?.foo.bar)', 'NOOP(x = [].foo.bar);'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = ("")?.foo.bar)', 'NOOP(x = "".foo.bar);'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = ({})?.foo())', 'NOOP(x = {}.foo());'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = /a/?.test("a"))', 'NOOP(x = /a/.test("a"));'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = ({})?.foo?.bar)', 'NOOP(x = {}.foo?.bar);'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = (() => 0)?.foo?.())', 'NOOP(x = (() => 0).foo?.());'],
    ['test_fold_opt_chain_non_nullish_base', 'NOOP(x = (({})?.foo)?.bar)', 'NOOP(x = {}.foo?.bar);'],
    ['test_fold_bitwise_op', 'NOOP(x = 1 & 1)', 'NOOP(x = 1);'],
    ['test_fold_bitwise_op', 'NOOP(x = 1 & 2)', 'NOOP(x = 0);'],
    ['test_fold_bitwise_op', 'NOOP(x = 3 & 1)', 'NOOP(x = 1);'],
    ['test_fold_bitwise_op', 'NOOP(x = 3 & 3)', 'NOOP(x = 3);'],
    ['test_fold_bitwise_op', 'NOOP(x = 1 | 1)', 'NOOP(x = 1);'],
    ['test_fold_bitwise_op', 'NOOP(x = 1 | 2)', 'NOOP(x = 3);'],
    ['test_fold_bitwise_op', 'NOOP(x = 3 | 1)', 'NOOP(x = 3);'],
    ['test_fold_bitwise_op', 'NOOP(x = 3 | 3)', 'NOOP(x = 3);'],
    ['test_fold_bitwise_op', 'NOOP(x = 1 ^ 1)', 'NOOP(x = 0);'],
    ['test_fold_bitwise_op', 'NOOP(x = 1 ^ 2)', 'NOOP(x = 3);'],
    ['test_fold_bitwise_op', 'NOOP(x = 3 ^ 1)', 'NOOP(x = 2);'],
    ['test_fold_bitwise_op', 'NOOP(x = 3 ^ 3)', 'NOOP(x = 0);'],
    ['test_fold_bitwise_op', 'NOOP(x = -1 & 0)', 'NOOP(x = 0);'],
    ['test_fold_bitwise_op', 'NOOP(x = 0 & -1)', 'NOOP(x = 0);'],
    ['test_fold_bitwise_op', 'NOOP(x = 1 & 4)', 'NOOP(x = 0);'],
    ['test_fold_bitwise_op', 'NOOP(x = 2 & 3)', 'NOOP(x = 2);'],
    ['test_fold_bitwise_op', 'NOOP(x = 1 & 1.1)', 'NOOP(x = 1);'],
    ['test_fold_bitwise_op', 'NOOP(x = 1.1 & 1)', 'NOOP(x = 1);'],
    ['test_fold_bitwise_op', 'NOOP(x = 1 & 3000000000)', 'NOOP(x = 0);'],
    ['test_fold_bitwise_op', 'NOOP(x = 3000000000 & 1)', 'NOOP(x = 0);'],
    ['test_fold_bitwise_op', 'NOOP(x = 1 | 4)', 'NOOP(x = 5);'],
    ['test_fold_bitwise_op', 'NOOP(x = 1 | 3)', 'NOOP(x = 3);'],
    ['test_fold_bitwise_op', 'NOOP(x = 1 | 1.1)', 'NOOP(x = 1);'],
    ['test_fold_bitwise_op', 'x = 1 | 3e9', 'x = -1294967295;'],
    ['test_fold_bitwise_op', 'NOOP(x = 1 | 3000000001)', 'NOOP(x = -1294967295);'],
    ['test_fold_bitwise_op', 'NOOP(x = 4294967295 | 0)', 'NOOP(x = -1);'],
    ['test_fold_bitwise_op', 'NOOP(x = -1 | 0)', 'NOOP(x = -1);'],
    ['test_fold_bitwise_op2', 'NOOP(x = y & 1 & 1)', 'NOOP(x = y & 1);'],
    ['test_fold_bitwise_op2', 'NOOP(x = y & 1 & 2)', 'NOOP(x = y & 0);'],
    ['test_fold_bitwise_op2', 'NOOP(x = y & 3 & 1)', 'NOOP(x = y & 1);'],
    ['test_fold_bitwise_op2', 'NOOP(x = 3 & y & 1)', 'NOOP(x = y & 1);'],
    ['test_fold_bitwise_op2', 'NOOP(x = y & 3 & 3)', 'NOOP(x = y & 3);'],
    ['test_fold_bitwise_op2', 'NOOP(x = 3 & y & 3)', 'NOOP(x = y & 3);'],
    ['test_fold_bitwise_op2', 'NOOP(x = y | 1 | 1)', 'NOOP(x = y | 1);'],
    ['test_fold_bitwise_op2', 'NOOP(x = y | 1 | 2)', 'NOOP(x = y | 3);'],
    ['test_fold_bitwise_op2', 'NOOP(x = y | 3 | 1)', 'NOOP(x = y | 3);'],
    ['test_fold_bitwise_op2', 'NOOP(x = 3 | y | 1)', 'NOOP(x = y | 3);'],
    ['test_fold_bitwise_op2', 'NOOP(x = y | 3 | 3)', 'NOOP(x = y | 3);'],
    ['test_fold_bitwise_op2', 'NOOP(x = 3 | y | 3)', 'NOOP(x = y | 3);'],
    ['test_fold_bitwise_op2', 'NOOP(x = y ^ 1 ^ 1)', 'NOOP(x = y ^ 0);'],
    ['test_fold_bitwise_op2', 'NOOP(x = y ^ 1 ^ 2)', 'NOOP(x = y ^ 3);'],
    ['test_fold_bitwise_op2', 'NOOP(x = y ^ 3 ^ 1)', 'NOOP(x = y ^ 2);'],
    ['test_fold_bitwise_op2', 'NOOP(x = 3 ^ y ^ 1)', 'NOOP(x = y ^ 2);'],
    ['test_fold_bitwise_op2', 'NOOP(x = y ^ 3 ^ 3)', 'NOOP(x = y ^ 0);'],
    ['test_fold_bitwise_op2', 'NOOP(x = 3 ^ y ^ 3)', 'NOOP(x = y ^ 0);'],
    ['test_fold_bitwise_op2', 'NOOP(x = Infinity | NaN)', 'NOOP(x = 0);'],
    ['test_fold_bitwise_op2', 'NOOP(x = 12 | NaN)', 'NOOP(x = 12);'],
    ['test_fold_bitwise_op_additional', 'NOOP(x = null & 1)', 'NOOP(x = 0);'],
    ['test_fold_bitwise_op_additional', 'NOOP(x = (2 ** 31 - 1) | 1)', 'NOOP(x = 2 ** 31 - 1 | 1);'],
    ['test_fold_bitwise_op_additional', 'NOOP(x = (2 ** 31) | 1)', 'NOOP(x = 2 ** 31 | 1);'],
    ['test_fold_bitwise_op_additional', 'NOOP((x - 1) & 1)', 'NOOP(x - 1 & 1);'],
    ['test_fold_bitwise_op_additional', 'NOOP((y >> 3) & 7)', 'NOOP(y >> 3 & 7);'],
    ['test_fold_bitwise_op_additional', 'NOOP((y & 3) & 7)', 'NOOP(y & 3);'],
    ['test_fold_bitwise_op_additional', 'NOOP((y | 3) & 7)', 'NOOP((y | 3) & 7);'],
    ['test_fold_bitwise_op_additional', 'NOOP(y | 3 & 7)', 'NOOP(y | 3);'],
    ['test_fold_bitwise_not', 'NOOP(~undefined)', 'NOOP(-1);'],
    ['test_fold_bitwise_not', 'NOOP(~null)', 'NOOP(-1);'],
    ['test_fold_bitwise_not', 'NOOP(~false)', 'NOOP(-1);'],
    ['test_fold_bitwise_not', 'NOOP(~true)', 'NOOP(-2);'],
    ['test_fold_bitwise_not', "NOOP(~'1')", 'NOOP(-2);'],
    ['test_fold_bitwise_not', "NOOP(~'-1')", 'NOOP(0);'],
    ['test_fold_bitwise_not', 'NOOP(~{})', 'NOOP(-1);'],
    ['test_fold_bit_shifts', 'NOOP(x = 1 << 0)', 'NOOP(x = 1);'],
    ['test_fold_bit_shifts', 'NOOP(x = -1 << 0)', 'NOOP(x = -1);'],
    ['test_fold_bit_shifts', 'NOOP(x = 1 << 1)', 'NOOP(x = 2);'],
    ['test_fold_bit_shifts', 'NOOP(x = 3 << 1)', 'NOOP(x = 6);'],
    ['test_fold_bit_shifts', 'NOOP(x = 1 << 8)', 'NOOP(x = 256);'],
    ['test_fold_bit_shifts', 'NOOP(x = 1 >> 0)', 'NOOP(x = 1);'],
    ['test_fold_bit_shifts', 'NOOP(x = -1 >> 0)', 'NOOP(x = -1);'],
    ['test_fold_bit_shifts', 'NOOP(x = 1 >> 1)', 'NOOP(x = 0);'],
    ['test_fold_bit_shifts', 'NOOP(x = 2 >> 1)', 'NOOP(x = 1);'],
    ['test_fold_bit_shifts', 'NOOP(x = 5 >> 1)', 'NOOP(x = 2);'],
    ['test_fold_bit_shifts', 'NOOP(x = 127 >> 3)', 'NOOP(x = 15);'],
    ['test_fold_bit_shifts', 'NOOP(x = 3 >> 1)', 'NOOP(x = 1);'],
    ['test_fold_bit_shifts', 'NOOP(x = 3 >> 2)', 'NOOP(x = 0);'],
    ['test_fold_bit_shifts', 'NOOP(x = 10 >> 1)', 'NOOP(x = 5);'],
    ['test_fold_bit_shifts', 'NOOP(x = 10 >> 2)', 'NOOP(x = 2);'],
    ['test_fold_bit_shifts', 'NOOP(x = 10 >> 5)', 'NOOP(x = 0);'],
    ['test_fold_bit_shifts', 'NOOP(x = 10 >>> 1)', 'NOOP(x = 5);'],
    ['test_fold_bit_shifts', 'NOOP(x = 10 >>> 2)', 'NOOP(x = 2);'],
    ['test_fold_bit_shifts', 'NOOP(x = 10 >>> 5)', 'NOOP(x = 0);'],
    ['test_fold_bit_shifts', 'NOOP(x = -1 >>> 1)', 'NOOP(x = -1 >>> 1);'],
    ['test_fold_bit_shifts', 'NOOP(x = -1 >>> 0)', 'NOOP(x = -1 >>> 0);'],
    ['test_fold_bit_shifts', 'NOOP(x = -2 >>> 0)', 'NOOP(x = -2 >>> 0);'],
    ['test_fold_bit_shifts', 'NOOP(x = 0x90000000 >>> 28)', 'NOOP(x = 9);'],
    ['test_fold_bit_shifts', 'NOOP(x = 0xffffffff << 0)', 'NOOP(x = -1);'],
    ['test_fold_bit_shifts', 'NOOP(x = 0xffffffff << 4)', 'NOOP(x = -16);'],
    ['test_fold_bit_shifts', 'NOOP(1 << 32)', 'NOOP(1);'],
    ['test_fold_bit_shifts', 'NOOP(1 << -1)', 'NOOP(1 << -1);'],
    ['test_fold_bit_shifts', 'NOOP(1 >> 32)', 'NOOP(1);'],
    ['test_fold_bit_shifts', 'NOOP(-2147483647 >>> 0)', 'NOOP(2147483649);'],
    ['test_fold_bit_shifts', 'NOOP(-2147483648 >>> 0)', 'NOOP(2147483648);'],
    ['test_fold_bit_shifts', 'NOOP(-2147483649 >>> 0)', 'NOOP(2147483647);'],
    ['test_fold_bit_shifts', 'NOOP(-4294967295 >>> 0)', 'NOOP(1);'],
    ['test_fold_bit_shifts', 'NOOP(-4294967296 >>> 0)', 'NOOP(0);'],
    ['test_fold_bit_shifts', 'NOOP(-4294967297 >>> 0)', 'NOOP(4294967295);'],
    ['test_fold_bit_shifts', 'NOOP(4294967295 >>> 0)', 'NOOP(4294967295);'],
    ['test_fold_bit_shifts', 'NOOP(4294967296 >>> 0)', 'NOOP(0);'],
    ['test_fold_bit_shifts', 'NOOP(4294967297 >>> 0)', 'NOOP(1);'],
    ['test_fold_bit_shifts', 'NOOP(8589934591 >>> 0)', 'NOOP(4294967295);'],
    ['test_fold_bit_shifts', 'NOOP(8589934592 >>> 0)', 'NOOP(0);'],
    ['test_fold_bit_shifts', 'NOOP(8589934593 >>> 0)', 'NOOP(1);'],
    ['test_fold_bit_shifts', 'NOOP(x = -1 << 1)', 'NOOP(x = -2);'],
    ['test_fold_bit_shifts', 'NOOP(x = -1 << 8)', 'NOOP(x = -256);'],
    ['test_fold_bit_shifts', 'NOOP(x = -1 >> 1)', 'NOOP(x = -1);'],
    ['test_fold_bit_shifts', 'NOOP(x = -2 >> 1)', 'NOOP(x = -1);'],
    ['test_fold_bit_shifts', 'NOOP(x = -1 >> 0)', 'NOOP(x = -1);'],
    ['test_string_add', "NOOP(x = 'a' + 'bc')", 'NOOP(x = "abc");'],
    ['test_string_add', "NOOP(x = '\\ud800' + 'y')", 'NOOP(x = "\\ud800" + "y");'],
    ['test_string_add', "NOOP(x = 'a' + 5)", 'NOOP(x = "a5");'],
    ['test_string_add', "NOOP(x = 5 + 'a')", 'NOOP(x = "5a");'],
    ['test_string_add', "NOOP(x = 'a' + 5n)", 'NOOP(x = "a5");'],
    ['test_string_add', "NOOP(x = 5n + 'a')", 'NOOP(x = "5a");'],
    ['test_string_add', "NOOP(x = 'a' + '')", 'NOOP(x = "a");'],
    ['test_string_add', "NOOP(x = 'a' + foo())", 'NOOP(x = "a" + foo());'],
    ['test_string_add', "NOOP(x = foo() + 'a' + 'b')", 'NOOP(x = foo() + "ab");'],
    ['test_string_add', "NOOP(x = (foo() + 'a') + 'b')", 'NOOP(x = foo() + "ab");'],
    ['test_string_add', "NOOP(x = foo() + 'a' + 'b' + 'cd' + bar())", 'NOOP(x = foo() + "abcd" + bar());'],
    ['test_string_add', "NOOP(x = foo() + 2 + 'b')", 'NOOP(x = foo() + 2 + "b");'],
    ['test_string_add', "NOOP(x = x - 'b' + 'c')", 'NOOP(x = x - "b" + "c");'],
    ['test_string_add', "NOOP(x = x * 'b' + 'c')", 'NOOP(x = x * "b" + "c");'],
    ['test_string_add', "NOOP(x = x % 'b' + 'c')", 'NOOP(x = x % "b" + "c");'],
    ['test_string_add', "NOOP(x = (x & 'b') + 'c')", 'NOOP(x = (x & "b") + "c");'],
    ['test_string_add', "NOOP(x = foo() + 'a' + 2)", 'NOOP(x = foo() + "a2");'],
    ['test_string_add', "NOOP(x = '' + null)", 'NOOP(x = "null");'],
    ['test_string_add', "NOOP(x = true + '' + false)", 'NOOP(x = "truefalse");'],
    ['test_string_add', "NOOP(x = '' + [])", 'NOOP(x = "");'],
    ['test_string_add', "NOOP(x = foo() + 'a' + 1 + 1)", 'NOOP(x = foo() + "a11");'],
    ['test_string_add', "NOOP(x = 1 + 1 + 'a')", 'NOOP(x = "2a");'],
    ['test_string_add', "NOOP(x = 1 + 1 + 'a')", 'NOOP(x = "2a");'],
    ['test_string_add', "NOOP(x = 'a' + (1 + 1))", 'NOOP(x = "a2");'],
    ['test_string_add', "NOOP(x = '_' + p1 + '_' + ('' + p2))", 'NOOP(x = "_" + p1 + "_" + ("" + p2));'],
    ['test_string_add', "NOOP(x = 'a' + ('_' + 1 + 1))", 'NOOP(x = "a_11");'],
    ['test_string_add', "NOOP(x = 'a' + ('_' + 1) + 1)", 'NOOP(x = "a_11");'],
    ['test_string_add', "NOOP(x = 1 + (p1 + '_') + ('' + p2))", 'NOOP(x = 1 + (p1 + "_") + ("" + p2));'],
    ['test_string_add', "NOOP(x = 1 + p1 + '_' + ('' + p2))", 'NOOP(x = 1 + p1 + "_" + ("" + p2));'],
    ['test_string_add', "NOOP(x = 1 + 'a' + p1)", 'NOOP(x = "1a" + p1);'],
    ['test_string_add', "NOOP(x = (p1 + (p2 + 'a')) + 'b')", 'NOOP(x = p1 + (p2 + "a") + "b");'],
    ['test_string_add', "NOOP('a' + ('b' + p1) + 1)", 'NOOP("a" + ("b" + p1) + 1);'],
    ['test_string_add', "NOOP(x = 'a' + ('b' + p1 + 'c'))", 'NOOP(x = "a" + ("b" + p1 + "c"));'],
    ['test_string_add', "NOOP(void 0 + '')", 'NOOP("undefined");'],
    ['test_string_add', 'NOOP(`${a}` + `${b}`)', 'NOOP(`${a}${b}`);'],
    ['test_string_add', 'NOOP(`${a}` + `${b}b`)', 'NOOP(`${a}${b}b`);'],
    ['test_string_add', 'NOOP(`${a}` + `b${b}`)', 'NOOP(`${a}b${b}`);'],
    ['test_string_add', 'NOOP(`${a}a` + `${b}`)', 'NOOP(`${a}a${b}`);'],
    ['test_string_add', 'NOOP(`${a}a` + `${b}b`)', 'NOOP(`${a}a${b}b`);'],
    ['test_string_add', 'NOOP(`${a}a` + `b${b}`)', 'NOOP(`${a}ab${b}`);'],
    ['test_string_add', 'NOOP(`a${a}` + `${b}`)', 'NOOP(`a${a}${b}`);'],
    ['test_string_add', 'NOOP(`a${a}` + `${b}b`)', 'NOOP(`a${a}${b}b`);'],
    ['test_string_add', 'NOOP(`a${a}` + `b${b}`)', 'NOOP(`a${a}b${b}`);'],
    ['test_string_add', 'NOOP(foo() + `${a}` + `${b}`)', 'NOOP(foo() + `${a}${b}`);'],
    ['test_string_add', "NOOP(x = 'a' + (4 + p1 + 'a'))", 'NOOP(x = "a" + (4 + p1 + "a"));'],
    ['test_string_add', 'NOOP(x = p1 / 3 + 4)', 'NOOP(x = p1 / 3 + 4);'],
    ['test_string_add', "NOOP(foo() + 3 + 'a' + foo())", 'NOOP(foo() + 3 + "a" + foo());'],
    ['test_string_add', "NOOP(x = 'a' + ('b' + p1 + p2))", 'NOOP(x = "a" + ("b" + p1 + p2));'],
    ['test_string_add', "NOOP(x = 1 + ('a' + p1))", 'NOOP(x = 1 + ("a" + p1));'],
    ['test_string_add', "NOOP(x = p1 + '' + p2)", 'NOOP(x = p1 + "" + p2);'],
    ['test_string_add', "NOOP(x = 'a' + (1 + p1))", 'NOOP(x = "a" + (1 + p1));'],
    ['test_string_add', "NOOP(x = (p2 + 'a') + (1 + p1))", 'NOOP(x = p2 + "a" + (1 + p1));'],
    ['test_string_add', "NOOP(x = (p2 + 'a') + (1 + p1 + p2))", 'NOOP(x = p2 + "a" + (1 + p1 + p2));'],
    ['test_string_add', "NOOP(x = (p2 + 'a') + (1 + (p1 + p2)))", 'NOOP(x = p2 + "a" + (1 + (p1 + p2)));'],
    ['test_fold_arithmetic', 'NOOP(1n+ +1n)', 'NOOP(1n + +1n);'],
    ['test_fold_arithmetic', 'NOOP(1n- -1n)', 'NOOP(1n - -1n);'],
    ['test_fold_arithmetic', 'NOOP(a- -b)', 'NOOP(a - -b);'],
    ['test_fold_arithmetic_infinity', 'NOOP(x=-Infinity-2)', 'NOOP(x = -Infinity);'],
    ['test_fold_arithmetic_infinity', 'NOOP(x=Infinity-2)', 'NOOP(x = Infinity);'],
    ['test_fold_arithmetic_infinity', 'NOOP(x=Infinity*5)', 'NOOP(x = Infinity);'],
    ['test_fold_arithmetic_infinity', 'NOOP(x = Infinity ** 2)', 'NOOP(x = Infinity);'],
    ['test_fold_arithmetic_infinity', 'NOOP(x = Infinity ** -2)', 'NOOP(x = 0);'],
    ['test_fold_arithmetic_infinity', 'NOOP(x = Infinity % Infinity)', 'NOOP(x = NaN);'],
    ['test_fold_arithmetic_infinity', 'NOOP(x = Infinity % 0)', 'NOOP(x = NaN);'],
    ['test_fold_add', 'NOOP(x = 10 + 20)', 'NOOP(x = 30);'],
    ['test_fold_add', 'NOOP(x = y + 10 + 20)', 'NOOP(x = y + 10 + 20);'],
    ['test_fold_add', 'NOOP(x = 1 + null)', 'NOOP(x = 1);'],
    ['test_fold_add', 'NOOP(x = null + 1)', 'NOOP(x = 1);'],
    ['test_fold_numeric_expression_only_if_shorter', 'NOOP(0.1 + 0.05)', 'NOOP(.1 + .05);'],
    ['test_fold_numeric_expression_only_if_shorter', 'NOOP(0.7 + 0.1)', 'NOOP(.7 + .1);'],
    ['test_fold_numeric_expression_only_if_shorter', 'NOOP(0.3 - 0.1)', 'NOOP(.3 - .1);'],
    ['test_fold_numeric_expression_only_if_shorter', 'NOOP(0.1 + (0.2 - 0.1) * 0.5)', 'NOOP(.1 + .05);'],
    ['test_fold_numeric_expression_only_if_shorter', 'NOOP(0.7 + (0.9 - 0.7) * 0.5)', 'NOOP(.8);'],
    ['test_fold_numeric_expression_only_if_shorter', 'NOOP(1e3 + 1e-10)', 'NOOP(1e3 + 1e-10);'],
    ['test_fold_numeric_expression_only_if_shorter', 'NOOP(1e12 + 1e12)', 'NOOP(2e12);'],
    ['test_fold_numeric_expression_only_if_shorter', 'NOOP(1e12 - 1e12)', 'NOOP(0);'],
    ['test_fold_numeric_expression_only_if_shorter', 'NOOP(0 + (0.1 + 0.05))', 'NOOP(0 + (.1 + .05));'],
    ['test_fold_numeric_expression_only_if_shorter', 'NOOP(f() + 0.05)', 'NOOP(f() + .05);'],
    ['test_fold_sub', 'NOOP(x = 10 - 20)', 'NOOP(x = -10);'],
    ['test_fold_multiply', 'NOOP(x = 2.25 * 3)', 'NOOP(x = 6.75);'],
    ['test_fold_multiply', 'NOOP(z = x * y)', 'NOOP(z = x * y);'],
    ['test_fold_multiply', 'NOOP(x = f() * 2)', 'NOOP(x = f() * 2);'],
    ['test_fold_multiply', 'NOOP(x = y * 5)', 'NOOP(x = y * 5);'],
    ['test_fold_multiply', 'NOOP(x = null * undefined)', 'NOOP(x = NaN);'],
    ['test_fold_multiply', 'NOOP(x = null * 1)', 'NOOP(x = 0);'],
    ['test_fold_multiply', 'NOOP(x = (null - 1) * 2)', 'NOOP(x = -2);'],
    ['test_fold_multiply', 'NOOP(x = (null + 1) * 2)', 'NOOP(x = 2);'],
    ['test_fold_multiply', 'x = y + (z * 24 * 60 * 60 * 1000)', 'x = y + z * 24 * 60 * 60 * 1e3;'],
    ['test_fold_multiply', 'NOOP(x = y + (z & 24 & 60 & 60 & 1000))', 'NOOP(x = y + (z & 8));'],
    ['test_fold_multiply', 'NOOP(x = -1 * -1)', 'NOOP(x = 1);'],
    ['test_fold_multiply', 'NOOP(x = 1 * -1)', 'NOOP(x = -1);'],
    ['test_fold_multiply', 'NOOP(x = 255 * 255)', 'NOOP(x = 65025);'],
    ['test_fold_multiply', 'NOOP(x = -255 * 255)', 'NOOP(x = -65025);'],
    ['test_fold_multiply', 'NOOP(x = -255 * -255)', 'NOOP(x = 65025);'],
    ['test_fold_multiply', 'NOOP(x = 256 * 255)', 'NOOP(x = 65280);'],
    ['test_fold_division', 'NOOP(x = Infinity / Infinity)', 'NOOP(x = NaN);'],
    ['test_fold_division', 'NOOP(x = Infinity / 0)', 'NOOP(x = Infinity);'],
    ['test_fold_division', 'NOOP(x = 1 / 0)', 'NOOP(x = 1 / 0);'],
    ['test_fold_division', 'NOOP(x = -1 / 0)', 'NOOP(x = -1 / 0);'],
    ['test_fold_division', 'NOOP(x = 1 / -0)', 'NOOP(x = -Infinity);'],
    ['test_fold_division', 'NOOP(x = -1 / -0)', 'NOOP(x = Infinity);'],
    ['test_fold_division', 'NOOP(x = 0 / 0)', 'NOOP(x = NaN);'],
    ['test_fold_division', 'NOOP(x = 360 / 360)', 'NOOP(x = 1);'],
    ['test_fold_division', 'NOOP(x = 10.5 / 0.75)', 'NOOP(x = 14);'],
    ['test_fold_division', 'NOOP(x = -10.5 / 0.75)', 'NOOP(x = -14);'],
    ['test_fold_division', 'NOOP(x = 0 / -1)', 'NOOP(x = -0);'],
    ['test_fold_division', 'NOOP(x = -0 / 1)', 'NOOP(x = -0);'],
    ['test_fold_division', 'NOOP(x = -5e-324 / 2)', 'NOOP(x = -0);'],
    ['test_fold_division', 'NOOP(x = 9007199254740992 / 2)', 'NOOP(x = 4503599627370496);'],
    ['test_fold_division', 'NOOP(x = 2 / 4)', 'NOOP(x = 2 / 4);'],
    ['test_fold_division', 'NOOP(x = 0.3 / 0.1)', 'NOOP(x = .3 / .1);'],
    ['test_fold_division', 'NOOP(x = 1e-323 / 2)', 'NOOP(x = 1e-323 / 2);'],
    ['test_fold_division', 'NOOP(x = 1 / 1e-15)', 'NOOP(x = 1 / 1e-15);'],
    ['test_fold_division', 'NOOP(x = 9007199254740991 / 0.5)', 'NOOP(x = 9007199254740991 / .5);'],
    ['test_fold_division', 'NOOP(x = f() / 2)', 'NOOP(x = f() / 2);'],
    ['test_fold_division', 'NOOP(x = (void f()) / 1)', 'NOOP(x = void f() / 1);'],
    ['test_fold_division', 'NOOP(x = ({ valueOf: f }) / 2)', 'NOOP(x = { valueOf: f } / 2);'],
    ['test_fold_division', 'NOOP(x = 4n / 2n)', 'NOOP(x = 4n / 2n);'],
    ['test_fold_division', 'NOOP(x = 4n / 2)', 'NOOP(x = 4n / 2);'],
    ['test_fold_division', 'NOOP(x = 4n / 0n)', 'NOOP(x = 4n / 0n);'],
    ['test_fold_division', 'NOOP(x = y / 2 / 4)', 'NOOP(x = y / 2 / 4);'],
    ['test_fold_remainder', 'NOOP(x = 3 % 2)', 'NOOP(x = 1);'],
    ['test_fold_remainder', 'NOOP(x = 3 % -2)', 'NOOP(x = 1);'],
    ['test_fold_remainder', 'NOOP(x = -1 % 3)', 'NOOP(x = -1);'],
    ['test_fold_remainder', 'NOOP(x = -1 % 1)', 'NOOP(x = -0);'],
    ['test_fold_remainder', 'NOOP(x = 5.5 % 1.5)', 'NOOP(x = 1);'],
    ['test_fold_remainder', 'NOOP(x = 1 % 0)', 'NOOP(x = NaN);'],
    ['test_fold_remainder', 'NOOP(x = 0 % 0)', 'NOOP(x = NaN);'],
    ['test_fold_remainder', 'NOOP(x = 18014398509481982 % 18014398509481984)', 'NOOP(x = 0x3ffffffffffffe % 0x40000000000000);'],
    ['test_fold_remainder', 'NOOP(x = 0.3 % 0.1)', 'NOOP(x = .3 % .1);'],
    ['test_fold_remainder', 'NOOP(x = f() % 2)', 'NOOP(x = f() % 2);'],
    ['test_fold_remainder', 'NOOP(x = 1 % f())', 'NOOP(x = 1 % f());'],
    ['test_fold_remainder', 'NOOP(x = 5n % 2n)', 'NOOP(x = 5n % 2n);'],
    ['test_fold_remainder', 'NOOP(x = 4n % 3n)', 'NOOP(x = 4n % 3n);'],
    ['test_fold_exponential', 'NOOP(x = 2 ** 3)', 'NOOP(x = 8);'],
    ['test_fold_exponential', 'NOOP(x = 10 ** 4)', 'NOOP(x = 1e4);'],
    ['test_fold_exponential', 'NOOP(x = (-2) ** 3)', 'NOOP(x = -8);'],
    ['test_fold_exponential', 'NOOP(x = 0.5 ** -2)', 'NOOP(x = .5 ** -2);'],
    ['test_fold_exponential', 'NOOP(x = 4 ** 0.5)', 'NOOP(x = 4 ** .5);'],
    ['test_fold_exponential', 'NOOP(x = (-5e-324) ** 3)', 'NOOP(x = (-5e-324) ** 3);'],
    ['test_fold_exponential', 'NOOP(x = 2 ** -3)', 'NOOP(x = 2 ** -3);'],
    ['test_fold_exponential', 'NOOP(x = 2 ** 50)', 'NOOP(x = 2 ** 50);'],
    ['test_fold_exponential', 'NOOP(x = 2 ** 55)', 'NOOP(x = 2 ** 55);'],
    ['test_fold_exponential', 'NOOP(x = 1e8 ** 2)', 'NOOP(x = 1e8 ** 2);'],
    ['test_fold_exponential', 'NOOP(x = 3 ** -1)', 'NOOP(x = 3 ** -1);'],
    ['test_fold_exponential', 'NOOP(x = f() ** 2)', 'NOOP(x = f() ** 2);'],
    ['test_fold_exponential', 'NOOP(x = 2 ** f())', 'NOOP(x = 2 ** f());'],
    ['test_fold_exponential', 'NOOP(x = ({ valueOf: f }) ** 2)', 'NOOP(x = { valueOf: f } ** 2);'],
    ['test_fold_exponential', 'NOOP(x = 2n ** 3n)', 'NOOP(x = 2n ** 3n);'],
    ['test_fold_exponential', 'NOOP(x = 2n ** 3)', 'NOOP(x = 2n ** 3);'],
    ['test_fold_exponential', 'NOOP(x = 2 ** 3n)', 'NOOP(x = 2 ** 3n);'],
    ['test_fold_exponential', 'NOOP(x = (void f()) ** 0)', 'NOOP(x = (void f()) ** 0);'],
    ['test_fold_exponential', 'function f(Infinity) {\n\treturn Infinity ** 0;\n}', ''],
    ['test_fold_exponential', 'NOOP(x = (-1) ** 0.5)', 'NOOP(x = (-1) ** .5);'],
    ['test_fold_exponential', 'NOOP(x = (-0) ** 3)', 'NOOP(x = -0);'],
    ['test_fold_exponential', 'NOOP(x = null ** 0)', 'NOOP(x = 1);'],
    ['test_fold_arithmetic_undefined_null_operands', 'NOOP(x = void 0 * 2)', 'NOOP(x = NaN);'],
    ['test_fold_arithmetic_undefined_null_operands', 'NOOP(x = void 0 - 1)', 'NOOP(x = NaN);'],
    ['test_fold_arithmetic_undefined_null_operands', 'NOOP(x = 2 / void 0)', 'NOOP(x = NaN);'],
    ['test_fold_arithmetic_undefined_null_operands', 'NOOP(x = void 0 % 2)', 'NOOP(x = NaN);'],
    ['test_fold_arithmetic_undefined_null_operands', 'NOOP(x = (void 0) ** 2)', 'NOOP(x = NaN);'],
    ['test_fold_arithmetic_undefined_null_operands', 'NOOP(x = null * 2)', 'NOOP(x = 0);'],
    ['test_fold_arithmetic_undefined_null_operands', "NOOP(x = '2' * '3')", 'NOOP(x = 6);'],
    ['test_fold_arithmetic_undefined_null_operands', 'NOOP(x = true * 5)', 'NOOP(x = 5);'],
    ['test_fold_arithmetic_undefined_null_operands', 'let a; NOOP(a * 2)', 'NOOP(NaN);'],
    ['test_fold_arithmetic_undefined_null_operands', 'NOOP(x = f() * 0)', 'NOOP(x = f() * 0);'],
    ['test_fold_arithmetic_undefined_null_operands', 'NOOP(x = 1n * 2)', 'NOOP(x = 1n * 2);'],
    ['test_fold_non_finite_result_with_shadowed_global', 'function f() {\n\tlet NaN = 1;\n\treturn 0 / 0;\n}', ''],
    ['test_fold_non_finite_result_with_shadowed_global', 'function f() {\n\tlet Infinity = 1;\n\treturn 1 / 0;\n}', ''],
    ['test_fold_shift_left', 'NOOP(1 << 3)', 'NOOP(8);'],
    ['test_fold_shift_left', 'NOOP(1.2345 << 0)', 'NOOP(1);'],
    ['test_fold_shift_left', 'NOOP(1 << 24)', 'NOOP(1 << 24);'],
    ['test_fold_shift_right', 'NOOP(2147483647 >> -32.1)', 'NOOP(2147483647);'],
    ['test_fold_shift_right_zero_fill', 'NOOP(10 >>> 1)', 'NOOP(5);'],
    ['test_fold_shift_right_zero_fill', 'NOOP(-1 >>> 0)', 'NOOP(-1 >>> 0);'],
    ['test_fold_left', 'NOOP((+x - 1) + 2)', 'NOOP(+x - 1 + 2);'],
    ['test_fold_left', 'NOOP((+x & 1) & 2)', 'NOOP(+x & 0);'],
    ['test_fold_array_length', 'NOOP(x = [].length)', 'NOOP(x = 0);'],
    ['test_fold_array_length', 'NOOP(x = [1,2,3].length)', 'NOOP(x = 3);'],
    ['test_fold_array_length', 'x = [a,b].length', 'x = [a, b].length;'],
    ['test_fold_array_length', "NOOP(x = 'abc'['length'])", 'NOOP(x = 3);'],
    ['test_fold_array_length', 'NOOP(x = [,,1].length)', 'NOOP(x = 3);'],
    ['test_fold_array_length', 'NOOP(x = [foo(), 0].length)', 'NOOP(x = [foo(), 0].length);'],
    ['test_fold_array_length', 'NOOP(x = y.length)', 'NOOP(x = y.length);'],
    ['test_fold_string_length', "NOOP(x = ''.length)", 'NOOP(x = 0);'],
    ['test_fold_string_length', "NOOP(x = '123'.length)", 'NOOP(x = 3);'],
    ['test_fold_string_length', "NOOP(x = '123\\u01dc'.length)", 'NOOP(x = 4);'],
    ['test_fold_instance_of', 'NOOP(64 instanceof Object)', 'NOOP(false);'],
    ['test_fold_instance_of', 'NOOP(64 instanceof Number)', 'NOOP(false);'],
    ['test_fold_instance_of', "NOOP('' instanceof Object)", 'NOOP(false);'],
    ['test_fold_instance_of', "NOOP('' instanceof String)", 'NOOP(false);'],
    ['test_fold_instance_of', 'NOOP(true instanceof Object)', 'NOOP(false);'],
    ['test_fold_instance_of', 'NOOP(true instanceof Boolean)', 'NOOP(false);'],
    ['test_fold_instance_of', 'NOOP(!0 instanceof Object)', 'NOOP(false);'],
    ['test_fold_instance_of', 'NOOP(!0 instanceof Boolean)', 'NOOP(false);'],
    ['test_fold_instance_of', 'NOOP(false instanceof Object)', 'NOOP(false);'],
    ['test_fold_instance_of', 'NOOP(null instanceof Object)', 'NOOP(false);'],
    ['test_fold_instance_of', 'NOOP(undefined instanceof Object)', 'NOOP(false);'],
    ['test_fold_instance_of', 'NOOP(NaN instanceof Object)', 'NOOP(false);'],
    ['test_fold_instance_of', 'NOOP(Infinity instanceof Object)', 'NOOP(false);'],
    ['test_fold_instance_of', 'NOOP([] instanceof Object)', 'NOOP(true);'],
    ['test_fold_instance_of', 'NOOP(({}) instanceof Object)', 'NOOP(true);'],
    ['test_fold_instance_of', 'NOOP(new Foo() instanceof Object)', 'NOOP(new Foo() instanceof Object);'],
    ['test_fold_instance_of', 'NOOP([] instanceof Foo)', 'NOOP([] instanceof Foo);'],
    ['test_fold_instance_of', 'NOOP(({}) instanceof Foo)', 'NOOP({} instanceof Foo);'],
    ['test_fold_instance_of', 'NOOP((function() {}) instanceof Object)', 'NOOP(true);'],
    ['test_fold_instance_of', 'NOOP(x instanceof Foo)', 'NOOP(x instanceof Foo);'],
    ['test_fold_instance_of', 'var x; foo(x instanceof Object)', 'var x; foo(x instanceof Object);'],
    ['test_fold_instance_of', 'NOOP(x instanceof Object)', 'NOOP(x instanceof Object);'],
    ['test_fold_instance_of', 'NOOP(0 instanceof Foo)', 'NOOP(0 instanceof Foo);'],
    ['test_fold_instance_of_additional', 'NOOP((typeof {}) instanceof Object)', 'NOOP(false);'],
    ['test_fold_instance_of_additional', 'NOOP((+{}) instanceof Number)', 'NOOP(false);'],
    [
        'test_fold_instance_of_additional',
        'NOOP(({ __proto__: null }) instanceof Object)',
        'NOOP({ __proto__: null } instanceof Object);',
    ],
    ['test_fold_instance_of_additional', 'NOOP(/foo/ instanceof Object)', 'NOOP(true);'],
    ['test_fold_instance_of_additional', 'NOOP((() => {}) instanceof Object)', 'NOOP(true);'],
    ['test_fold_instance_of_additional', 'NOOP((function(){}) instanceof Object)', 'NOOP(true);'],
    ['test_fold_instance_of_additional', 'NOOP((class{}) instanceof Object)', 'NOOP(true);'],
    ['test_fold_left_child_op', 'NOOP(x & Infinity & 2)', 'NOOP(x & 0);'],
    ['test_fold_left_child_op', 'NOOP(x - Infinity - 2)', 'NOOP(x - Infinity - 2);'],
    ['test_fold_left_child_op', 'NOOP(x - 1 + Infinity)', 'NOOP(x - 1 + Infinity);'],
    ['test_fold_left_child_op', 'NOOP(x - 2 + 1)', 'NOOP(x - 2 + 1);'],
    ['test_fold_left_child_op', 'NOOP(x - 2 + 3)', 'NOOP(x - 2 + 3);'],
    ['test_fold_left_child_op', 'NOOP(1 + x - 2 + 1)', 'NOOP(1 + x - 2 + 1);'],
    ['test_fold_left_child_op', 'NOOP(1 + x - 2 + 3)', 'NOOP(1 + x - 2 + 3);'],
    ['test_fold_left_child_op', 'NOOP(1 + x - 2 + 3 - 1)', 'NOOP(1 + x - 2 + 3 - 1);'],
    ['test_fold_left_child_op', 'NOOP(f(x)-0)', 'NOOP(f(x) - 0);'],
    ['test_fold_left_child_op', 'NOOP(x-0-0)', 'NOOP(x - 0 - 0);'],
    ['test_fold_left_child_op', 'NOOP(x+2-2+2)', 'NOOP(x + 2 - 2 + 2);'],
    ['test_fold_left_child_op', 'NOOP(x+2-2+2-2)', 'NOOP(x + 2 - 2 + 2 - 2);'],
    ['test_fold_left_child_op', 'NOOP(x-2+2)', 'NOOP(x - 2 + 2);'],
    ['test_fold_left_child_op', 'NOOP(x-2+2-2)', 'NOOP(x - 2 + 2 - 2);'],
    ['test_fold_left_child_op', 'NOOP(x-2+2-2+2)', 'NOOP(x - 2 + 2 - 2 + 2);'],
    ['test_fold_left_child_op', 'NOOP(1+x-0-na_n)', 'NOOP(1 + x - 0 - na_n);'],
    ['test_fold_left_child_op', 'NOOP(1+f(x)-0-na_n)', 'NOOP(1 + f(x) - 0 - na_n);'],
    ['test_fold_left_child_op', 'NOOP(1+x-0+na_n)', 'NOOP(1 + x - 0 + na_n);'],
    ['test_fold_left_child_op', 'NOOP(1+f(x)-0+na_n)', 'NOOP(1 + f(x) - 0 + na_n);'],
    ['test_fold_left_child_op', 'NOOP(1+x+na_n)', 'NOOP(1 + x + na_n);'],
    ['test_fold_left_child_op', 'NOOP(x+2-2)', 'NOOP(x + 2 - 2);'],
    ['test_fold_left_child_op', 'NOOP(x+2)', 'NOOP(x + 2);'],
    ['test_fold_left_child_op', 'NOOP(x-2)', 'NOOP(x - 2);'],
    ['test_associative_fold_constants_with_variables', 'NOOP(alert(x * 12 * 20))', 'NOOP(alert(x * 12 * 20));'],
    ['test_associative_fold_constants_with_variables', 'NOOP(alert(12 * x * 20))', 'NOOP(alert(12 * x * 20));'],
    ['test_associative_fold_constants_with_variables', 'NOOP(alert(x + 12 + 20))', 'NOOP(alert(x + 12 + 20));'],
    ['test_associative_fold_constants_with_variables', 'NOOP(alert(12 + x + 20))', 'NOOP(alert(12 + x + 20));'],
    ['test_associative_fold_constants_with_variables', 'NOOP(alert(x & 12 & 20))', 'NOOP(alert(x & 4));'],
    ['test_associative_fold_constants_with_variables', 'NOOP(alert(12 & x & 20))', 'NOOP(alert(x & 4));'],
    ['test_to_number', "NOOP(x = +'')", 'NOOP(x = 0);'],
    ['test_to_number', "NOOP(x = +'+Infinity')", 'NOOP(x = Infinity);'],
    ['test_to_number', "NOOP(x = +'-Infinity')", 'NOOP(x = -Infinity);'],
    ['test_number_constructor', 'NOOP(Number(undefined))', 'NOOP(NaN);'],
    ['test_number_constructor', 'NOOP(Number(void 0))', 'NOOP(NaN);'],
    ['test_number_constructor', 'NOOP(Number(null))', 'NOOP(0);'],
    ['test_number_constructor', 'NOOP(Number(true))', 'NOOP(1);'],
    ['test_number_constructor', 'NOOP(Number(false))', 'NOOP(0);'],
    ['test_number_constructor', "NOOP(Number('a'))", 'NOOP(NaN);'],
    ['test_number_constructor', "NOOP(Number('1'))", 'NOOP(1);'],
    ['test_number_constructor', 'var Number; NOOP(Number(1))', 'var Number; NOOP(Number(1));'],
    ['test_fold_useless_string_addition', 'NOOP(typeof foo)', 'NOOP(typeof foo);'],
    ['test_fold_useless_string_addition', "NOOP(typeof foo + '123')", 'NOOP(typeof foo + "123");'],
    ['test_fold_useless_string_addition', "NOOP(typeof foo + '')", 'NOOP(typeof foo);'],
    ['test_fold_useless_string_addition', "NOOP('' + typeof foo)", 'NOOP(typeof foo);'],
    ['test_fold_useless_string_addition', 'NOOP(typeof foo + ``)', 'NOOP(typeof foo + ``);'],
    ['test_fold_useless_string_addition', 'NOOP(`` + typeof foo)', 'NOOP(`` + typeof foo);'],
    ['test_fold_useless_string_addition', 'NOOP(typeof foo + [])', 'NOOP(typeof foo);'],
    ['test_fold_useless_string_addition', 'NOOP([] + typeof foo)', 'NOOP(typeof foo);'],
    ['test_fold_useless_string_addition', "NOOP((foo ? 'a' : 'b') + '')", 'NOOP(foo ? "a" : "b");'],
    ['test_fold_useless_string_addition', "NOOP(typeof foo - '')", 'NOOP(typeof foo - "");'],
    ['test_fold_same_typeof', 'NOOP(typeof foo === typeof bar)', 'NOOP(typeof foo === typeof bar);'],
    ['test_fold_same_typeof', 'NOOP(typeof foo !== typeof bar)', 'NOOP(typeof foo !== typeof bar);'],
    ['test_fold_same_typeof', 'NOOP(typeof foo.bar === typeof foo.bar)', 'NOOP(typeof foo.bar === typeof foo.bar);'],
    ['test_fold_same_typeof', 'NOOP(typeof foo.bar !== typeof foo.bar)', 'NOOP(typeof foo.bar !== typeof foo.bar);'],
    ['test_fold_invalid_typeof_comparison', 'NOOP(typeof foo == 123)', 'NOOP(false);'],
    ['test_fold_invalid_typeof_comparison', "NOOP(typeof foo == '123')", 'NOOP(false);'],
    ['test_fold_invalid_typeof_comparison', 'NOOP(typeof foo === null)', 'NOOP(false);'],
    ['test_fold_invalid_typeof_comparison', 'NOOP(typeof foo === undefined)', 'NOOP(false);'],
    ['test_fold_invalid_typeof_comparison', 'NOOP(typeof foo !== 123)', 'NOOP(true);'],
    ['test_fold_invalid_typeof_comparison', "NOOP(typeof foo !== '123')", 'NOOP(true);'],
    ['test_fold_invalid_typeof_comparison', 'NOOP(typeof foo != null)', 'NOOP(true);'],
    ['test_fold_invalid_typeof_comparison', 'NOOP(typeof foo != undefined)', 'NOOP(true);'],
    ['test_fold_invalid_typeof_comparison', "NOOP(typeof foo === 'string')", 'NOOP(typeof foo === "string");'],
    ['test_fold_invalid_typeof_comparison', "NOOP(typeof foo === 'number')", 'NOOP(typeof foo === "number");'],
    ['test_fold_invalid_typeof_comparison', 'NOOP(typeof foo === [1])', 'NOOP(false);'],
    ['test_fold_invalid_typeof_comparison', 'NOOP(typeof foo !== [1])', 'NOOP(true);'],
    ['test_fold_invalid_typeof_comparison', "NOOP(typeof foo === ['object'])", 'NOOP(false);'],
    ['test_fold_invalid_typeof_comparison', "NOOP(typeof foo == ['object'])", 'NOOP(typeof foo == ["object"]);'],
    ['test_fold_invalid_typeof_comparison', "NOOP(typeof foo != ['object'])", 'NOOP(typeof foo != ["object"]);'],
    ['test_fold_invalid_typeof_comparison', "NOOP(typeof foo == ['function'])", 'NOOP(typeof foo == ["function"]);'],
    ['test_fold_invalid_typeof_comparison', "NOOP(typeof foo == [['object']])", 'NOOP(typeof foo == [["object"]]);'],
    [
        'test_fold_invalid_typeof_comparison',
        "NOOP(typeof foo == { toString: () => 'object' })",
        'NOOP(typeof foo == { toString: () => "object" });',
    ],
    ['test_fold_invalid_typeof_comparison', 'NOOP(typeof foo == [x])', 'NOOP(typeof foo == [x]);'],
    ['test_fold_invalid_typeof_comparison', 'NOOP(typeof foo == [1])', 'NOOP(false);'],
    ['test_fold_invalid_typeof_comparison', "NOOP(typeof foo == ['x'])", 'NOOP(false);'],
    ['test_fold_invalid_typeof_comparison', 'NOOP(typeof foo == [])', 'NOOP(false);'],
    ['test_fold_invalid_typeof_comparison', 'NOOP(typeof foo == [1, 2])', 'NOOP(false);'],
    ['test_fold_invalid_typeof_comparison', 'NOOP(typeof foo == {})', 'NOOP(false);'],
    ['test_fold_keep_side_effects_in_typeof_comparison', 'NOOP(typeof f() == 1)', 'NOOP(typeof f() == 1);'],
    ['test_fold_keep_side_effects_in_typeof_comparison', "NOOP(typeof f() === 'asd')", 'NOOP(typeof f() === "asd");'],
    ['test_fold_keep_side_effects_in_typeof_comparison', 'NOOP(typeof x === [f()])', 'NOOP(typeof x === [f()]);'],
    ['test_issue_8782', 'NOOP(+(void unknown()))', 'NOOP(+void unknown());'],
    ['test_inline_values_in_template_literal', 'NOOP(`foo${1}`)', 'NOOP(`foo1`);'],
    ['test_inline_values_in_template_literal', 'NOOP(`foo${1}bar`)', 'NOOP(`foo1bar`);'],
    ['test_inline_values_in_template_literal', 'NOOP(`foo${1}bar${2}baz`)', 'NOOP(`foo1bar2baz`);'],
    ['test_inline_values_in_template_literal', 'NOOP(`foo${1}bar${2}baz${3}qux`)', 'NOOP(`foo1bar2baz3qux`);'],
    ['test_inline_values_in_template_literal', 'NOOP(`foo${1}${i}`)', 'NOOP(`foo1${i}`);'],
    ['test_inline_values_in_template_literal', "NOOP(`foo${'${}'}`)", 'NOOP(`foo\\${}`);'],
    ['test_inline_values_in_template_literal', "NOOP(`foo${'${}'}${i}`)", 'NOOP(`foo\\${}${i}`);'],
    ['test_inline_values_in_template_literal', 'NOOP(foo`foo${1}bar`)', 'NOOP(foo`foo${1}bar`);'],
    [
        'test_fold_object_spread_drop_walks_argument_refs',
        "function f() { let x = 'a'; ({...function(){ x = 'b' }}); return x; }",
        '',
    ],
    [
        'test_fold_object_spread_drop_walks_argument_refs',
        "function f() { let x = 'a'; ({...{__proto__: function(){ x = 'b' }}}); return x; }",
        '',
    ],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 1n & 1n)', 'NOOP(x = 1n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 1n & 2n)', 'NOOP(x = 0n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 3n & 1n)', 'NOOP(x = 1n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 3n & 3n)', 'NOOP(x = 3n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 1n | 1n)', 'NOOP(x = 1n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 1n | 2n)', 'NOOP(x = 3n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 1n | 3n)', 'NOOP(x = 3n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 3n | 1n)', 'NOOP(x = 3n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 3n | 3n)', 'NOOP(x = 3n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 1n | 4n)', 'NOOP(x = 5n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 1n ^ 1n)', 'NOOP(x = 0n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 1n ^ 2n)', 'NOOP(x = 3n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 3n ^ 1n)', 'NOOP(x = 2n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 3n ^ 3n)', 'NOOP(x = 0n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = -1n & 0n)', 'NOOP(x = 0n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 0n & -1n)', 'NOOP(x = 0n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 1n & 4n)', 'NOOP(x = 0n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 2n & 3n)', 'NOOP(x = 2n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 1n & 3000000000n)', 'NOOP(x = 0n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 3000000000n & 1n)', 'NOOP(x = 0n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 1n | 3000000001n)', 'NOOP(x = 3000000001n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 4294967295n | 0n)', 'NOOP(x = 4294967295n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = y & 1n & 1n)', 'NOOP(x = y & 1n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = y & 1n & 2n)', 'NOOP(x = y & 0n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = y & 3n & 1n)', 'NOOP(x = y & 1n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 3n & y & 1n)', 'NOOP(x = y & 1n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = y & 3n & 3n)', 'NOOP(x = y & 3n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 3n & y & 3n)', 'NOOP(x = y & 3n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = y | 1n | 1n)', 'NOOP(x = y | 1n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = y | 1n | 2n)', 'NOOP(x = y | 3n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = y | 3n | 1n)', 'NOOP(x = y | 3n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 3n | y | 1n)', 'NOOP(x = y | 3n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = y | 3n | 3n)', 'NOOP(x = y | 3n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 3n | y | 3n)', 'NOOP(x = y | 3n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = y ^ 1n ^ 1n)', 'NOOP(x = y ^ 0n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = y ^ 1n ^ 2n)', 'NOOP(x = y ^ 3n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = y ^ 3n ^ 1n)', 'NOOP(x = y ^ 2n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 3n ^ y ^ 1n)', 'NOOP(x = y ^ 2n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = y ^ 3n ^ 3n)', 'NOOP(x = y ^ 0n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(x = 3n ^ y ^ 3n)', 'NOOP(x = y ^ 0n);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(1n & 1)', 'NOOP(1n & 1);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(1n | 1)', 'NOOP(1n | 1);'],
    ['test_fold_bitwise_op_with_big_int', 'NOOP(1n ^ 1)', 'NOOP(1n ^ 1);'],
    ['test_bigint_number_comparison', 'NOOP(1n < 2)', 'NOOP(true);'],
    ['test_bigint_number_comparison', 'NOOP(1n > 2)', 'NOOP(false);'],
    ['test_bigint_number_comparison', 'NOOP(1n == 1)', 'NOOP(true);'],
    ['test_bigint_number_comparison', 'NOOP(1n == 2)', 'NOOP(false);'],
    ['test_bigint_number_comparison', 'NOOP(1n < 1.1)', 'NOOP(true);'],
    ['test_bigint_number_comparison', 'NOOP(1n < 1.9)', 'NOOP(true);'],
    ['test_bigint_number_comparison', 'NOOP(1n < 0.9)', 'NOOP(false);'],
    ['test_bigint_number_comparison', 'NOOP(-1n < -1.1)', 'NOOP(false);'],
    ['test_bigint_number_comparison', 'NOOP(-1n < -1.9)', 'NOOP(false);'],
    ['test_bigint_number_comparison', 'NOOP(-1n < -0.9)', 'NOOP(true);'],
    ['test_bigint_number_comparison', 'NOOP(1n > 1.1)', 'NOOP(false);'],
    ['test_bigint_number_comparison', 'NOOP(1n > 0.9)', 'NOOP(true);'],
    ['test_bigint_number_comparison', 'NOOP(-1n > -1.1)', 'NOOP(true);'],
    ['test_bigint_number_comparison', 'NOOP(-1n > -0.9)', 'NOOP(false);'],
    ['test_bigint_number_comparison', 'NOOP(1n < Infinity)', 'NOOP(true);'],
    ['test_bigint_number_comparison', 'NOOP(1n > Infinity)', 'NOOP(false);'],
    ['test_bigint_number_comparison', 'NOOP(1n < -Infinity)', 'NOOP(false);'],
    ['test_bigint_number_comparison', 'NOOP(1n > -Infinity)', 'NOOP(true);'],
    ['test_bigint_number_comparison', 'NOOP(1n < null)', 'NOOP(false);'],
    ['test_bigint_number_comparison', 'NOOP(1n > null)', 'NOOP(true);'],
    ['test_bigint_string_comparison', "NOOP(1n < '2')", 'NOOP(true);'],
    ['test_bigint_string_comparison', "NOOP(2n > '1')", 'NOOP(true);'],
    ['test_bigint_string_comparison', "NOOP(123n > '34')", 'NOOP(true);'],
    ['test_bigint_string_comparison', "NOOP(1n == '1')", 'NOOP(true);'],
    ['test_bigint_string_comparison', "NOOP(1n == '2')", 'NOOP(false);'],
    ['test_bigint_string_comparison', "NOOP(1n != '1')", 'NOOP(false);'],
    ['test_bigint_string_comparison', "NOOP(1n === '1')", 'NOOP(false);'],
    ['test_bigint_string_comparison', "NOOP(1n !== '1')", 'NOOP(true);'],
    ['test_string_bigint_comparison', "NOOP('1' < 2n)", 'NOOP(true);'],
    ['test_string_bigint_comparison', "NOOP('2' > 1n)", 'NOOP(true);'],
    ['test_string_bigint_comparison', "NOOP('123' > 34n)", 'NOOP(true);'],
    ['test_string_bigint_comparison', "NOOP('1' == 1n)", 'NOOP(true);'],
    ['test_string_bigint_comparison', "NOOP('1' == 2n)", 'NOOP(false);'],
    ['test_string_bigint_comparison', "NOOP('1' != 1n)", 'NOOP(false);'],
    ['test_string_bigint_comparison', "NOOP('1' === 1n)", 'NOOP(false);'],
    ['test_string_bigint_comparison', "NOOP('1' !== 1n)", 'NOOP(true);'],
    ['test_fold_object_spread', 'NOOP(({ z, ...a }))', 'NOOP({ z, ...a });'],
    ['test_fold_object_spread', "NOOP(({ z, ...'abc' }))", 'NOOP({ z, ..."abc" });'],
    ['test_fold_object_spread', 'NOOP(({ a: 0, ...{ b: 1 } }))', 'NOOP({ a: 0, b: 1 });'],
    ['test_fold_object_spread', 'NOOP(({ a: 0, ...{ b: 1, ...{ c: 2 } } }))', 'NOOP({ a: 0, b: 1, c: 2 });'],
    ['test_fold_object_spread', 'NOOP(({ a: 0, ...{ a: 1 } }))', 'NOOP({ a: 0, a: 1 });'],
    ['test_fold_object_spread', 'NOOP(({ a: foo(), ...{ a: bar() } }))', 'NOOP({ a: foo(), a: bar() });'],
    ['test_fold_object_spread', 'NOOP(({ ...{ get a() { return 0 } } }))', 'NOOP({ ...{ get a() { return 0; } } });'],
    ['test_fold_object_spread', 'NOOP(({ ...{ __proto__: null } }))', 'NOOP({});'],
    ['test_fold_object_spread', "NOOP(({ ...{ '__proto__': null } }))", 'NOOP({});'],
    [
        'test_fold_object_spread',
        'NOOP(({ a: foo(), ...{ __proto__: bar() }, b: baz() }))',
        'NOOP({ a: foo(), ...{ __proto__: bar() }, b: baz() });',
    ],
    ['test_fold_object_spread', 'NOOP(({ ...{ __proto__() {} } }))', 'NOOP({ __proto__() {} });'],
    ['test_fold_object_spread', "NOOP(({ ...{ ['__proto__']: null } }))", 'NOOP({ ["__proto__"]: null });'],
];

const DEAD_CODE_ELIMINATION: Case[] = [
    ['dce_logical_expression', "('production' == 'development') && bar()", ''],
    ['dce_logical_expression', "('production' == 'production') && bar()", 'bar();'],
    ['dce_logical_expression', "var foo = ('production' == 'development') && bar(); baz(foo)", 'baz(false);'],
    ['dce_logical_expression', "var foo = ('production' == 'production') && bar(); baz(foo)", 'var foo = bar(); baz(foo);'],
    ['dce_logical_expression', "foo = ('production' == 'development') && bar()", 'foo = false;'],
    ['dce_logical_expression', "foo = ('production' == 'production') && bar()", 'foo = bar();'],
    [
        'dce_logical_expression',
        "const x = 'keep'; const y = 'remove'; foo(x || y), foo(y && x)",
        'const x = "keep"; foo(x), foo(x);',
    ],
    [
        'pure_comment_re_evaluated_after_string_concat_fold',
        "var r = new RegExp('foo' + 'bar'); foo(r)",
        'var r = /* @__PURE__ */ new RegExp("foobar"); foo(r);',
    ],
    ['fold_number_nan', 'foo(Number.NaN)', 'foo(NaN);'],
    ['fold_number_nan', 'let Number; foo(Number.NaN)', 'let Number; foo(Number.NaN);'],
    [
        'preserve_iife_in_dce_mode',
        'export const exec = /* @__PURE__ */ (() => _M.exec)();',
        'export const exec = /* @__PURE__ */ (() => _M.exec)();',
    ],
    [
        'preserve_iife_in_dce_mode',
        'export const x = /* @__PURE__ */ (() => foo()?.bar())();',
        'export const x = /* @__PURE__ */ (() => foo()?.bar())();',
    ],
    [
        'preserve_iife_in_dce_mode',
        'export const x = /* @__PURE__ */ (() => foo`tpl`)();',
        'export const x = /* @__PURE__ */ (() => foo`tpl`)();',
    ],
    [
        'preserve_iife_in_dce_mode',
        'export const x = /* @__PURE__ */ (() => (a(), b()))();',
        'export const x = /* @__PURE__ */ (() => (a(), b()))();',
    ],
    [
        'preserve_iife_in_dce_mode',
        'export const x = /* @__PURE__ */ (() => c ? a() : b())();',
        'export const x = /* @__PURE__ */ (() => c ? a() : b())();',
    ],
    [
        'preserve_iife_in_dce_mode',
        'export const x = /* @__PURE__ */ (() => a ? b : c)();',
        'export const x = /* @__PURE__ */ (() => a ? b : c)();',
    ],
    [
        'preserve_iife_in_dce_mode',
        'export const x = /* @__PURE__ */ (() => foo())();',
        'export const x = /* @__PURE__ */ (() => foo())();',
    ],
    [
        'preserve_iife_in_dce_mode',
        'export const x = /* @__PURE__ */ (() => new Foo())();',
        'export const x = /* @__PURE__ */ (() => new Foo())();',
    ],
    [
        'preserve_iife_in_dce_mode',
        'export const x = /* @__PURE__ */ (() => foo(bar()))();',
        'export const x = /* @__PURE__ */ (() => foo(bar()))();',
    ],
    [
        'preserve_iife_in_dce_mode',
        'export const x = /* @__PURE__ */ (() => new Foo(bar()))();',
        'export const x = /* @__PURE__ */ (() => new Foo(bar()))();',
    ],
    [
        'preserve_iife_in_dce_mode',
        'export const x = /* @__PURE__ */ (() => 42)();',
        'export const x = /* @__PURE__ */ (() => 42)();',
    ],
    [
        'preserve_iife_in_dce_mode',
        'export const x = /* @__PURE__ */ (() => [1, 2, 3])();',
        'export const x = /* @__PURE__ */ (() => [1, 2, 3])();',
    ],
    [
        'preserve_iife_in_dce_mode',
        'export const x = /* @__PURE__ */ (() => ({ a: 1 }))();',
        'export const x = /* @__PURE__ */ (() => ({ a: 1 }))();',
    ],
    ['preserve_iife_in_dce_mode', 'export const x = (() => foo())();', 'export const x = (() => foo())();'],
    ['preserve_iife_in_dce_mode', 'export const x = (() => [1, 2, 3])();', 'export const x = (() => [1, 2, 3])();'],
    ['preserve_iife_in_dce_mode', 'export const x = (() => 42)();', 'export const x = (() => 42)();'],
    ['preserve_iife_in_dce_mode', 'export const x = (() => { foo(); })();', 'export const x = (() => { foo(); })();'],
    [
        'preserve_iife_in_dce_mode',
        'export const x = (() => { return foo(); })();',
        'export const x = (() => { return foo(); })();',
    ],
    [
        'preserve_iife_in_dce_mode',
        '(function () { function t() {} return t })();',
        '(function () { function t() {} return t; }());',
    ],
    ['preserve_iife_in_dce_mode', '(function () { return 1 })();', '(function () { return 1; }());'],
    ['preserve_iife_in_dce_mode', 'var u = (function () { return 1 })();', '(function () { return 1; }());'],
    ['preserve_iife_in_dce_mode', '(function () { return 1 })(), foo();', '(function () { return 1; }(), foo());'],
    [
        'preserve_iife_in_dce_mode',
        'for (var u = (function () { return 1 })(); cond;) bar();',
        'for (var u = function () { return 1; }(); cond;) bar();',
    ],
    ['drop_optional_chain_on_non_nullish_base', '({})?.foo;', '({}.foo);'],
    ['drop_optional_chain_on_non_nullish_base', 'export const v = (foo(), {})?.bar', 'export const v = (foo(), {}).bar;'],
    ['drop_optional_chain_on_non_nullish_base', 'export const v = null?.foo.bar', 'export const v = void 0;'],
    ['drop_optional_chain_on_non_nullish_base', 'export const v = []?.foo.bar', 'export const v = [].foo.bar;'],
    [
        'fold_optional_chain_on_undefined_let_binding',
        'let slot; export function call() { slot?.() }',
        'export function call() {}',
    ],
    [
        'fold_optional_chain_on_undefined_let_binding',
        'let slot; export function call() { slot?.foo }',
        'export function call() {}',
    ],
    [
        'fold_optional_chain_on_undefined_let_binding',
        'let slot; export function call() { slot?.[foo()] }',
        'export function call() {}',
    ],
    [
        'fold_optional_chain_on_undefined_let_binding',
        'let slot; export function setSlot(v) { slot = v } export function call() { slot?.() }',
        'let slot; export function setSlot(v) { slot = v; } export function call() { slot?.(); }',
    ],
    [
        'fold_optional_chain_on_null_const_binding',
        'const slot = null; export function call() { slot?.() }',
        'export function call() {}',
    ],
    [
        'fold_optional_chain_on_null_const_binding',
        'const slot = null; export function call() { slot?.foo }',
        'export function call() {}',
    ],
    [
        'fold_coalesce_on_tracked_non_nullish_binding',
        "let s = 'hello'; export function a() { return s ?? other() } export function b() { return s ?? other() }",
        'let s = "hello"; export function a() { return s; } export function b() { return s; }',
    ],
    [
        'fold_coalesce_on_tracked_non_nullish_binding',
        'let n = 5n; export function a() { return n ?? other() } export function b() { return n ?? other() }',
        'let n = 5n; export function a() { return n; } export function b() { return n; }',
    ],
    [
        'does_not_duplicate_large_tracked_strings_when_folding_addition',
        "const p = 'PAYLOADpayload0123456789PAYLOADpayload0123456789'; export const a = atob(p); export const b = 'y' + p;",
        'const p = "PAYLOADpayload0123456789PAYLOADpayload0123456789"; export const a = atob(p); export const b = "y" + p;',
    ],
    [
        'does_not_duplicate_large_tracked_strings_when_folding_addition',
        "const p = 'PAYLOADpayload0123456789PAYLOADpayload0123456789'; export const a = atob(p); export const b = 'x' + ('y' + p);",
        'const p = "PAYLOADpayload0123456789PAYLOADpayload0123456789"; export const a = atob(p); export const b = "x" + ("y" + p);',
    ],
    [
        'does_not_duplicate_large_tracked_strings_when_folding_addition',
        "const p = 'PAYLOADpayload0123456789PAYLOADpayload0123456789'; export const b = 'y' + p;",
        'export const b = "yPAYLOADpayload0123456789PAYLOADpayload0123456789";',
    ],
    [
        'does_not_duplicate_large_tracked_strings_when_folding_addition',
        "const p = 'abc'; export const a = atob(p); export const b = 'y' + p;",
        'const p = "abc"; export const a = atob(p); export const b = "yabc";',
    ],
    [
        'dce_inline_template_literal_does_not_create_octal_escape',
        'export function makeKey(messageId, correlationId) { return `${messageId}\\0${correlationId}\\0${0}`; }',
        'export function makeKey(messageId, correlationId) { return `${messageId}\\0${correlationId}\\x000`; }',
    ],
    [
        'dce_inline_template_literal_does_not_create_octal_escape',
        'export function makeKey(messageId) { return `${messageId}\\\\0${0}`; }',
        'export function makeKey(messageId) { return `${messageId}\\\\00`; }',
    ],
    [
        'dce_inline_template_literal_does_not_create_octal_escape',
        "export function makeKey(messageId) { return `${messageId}\\0${''}0`; }",
        'export function makeKey(messageId) { return `${messageId}\\x000`; }',
    ],
    [
        'dce_inline_template_literal_does_not_create_octal_escape',
        "export function makeKey(messageId) { return `${messageId}\\0${''}${0}`; }",
        'export function makeKey(messageId) { return `${messageId}\\x000`; }',
    ],
    [
        'dce_inline_template_literal_does_not_create_octal_escape',
        'export function makeKey(messageId) { return `${messageId}\\0${sideEffect()}`; }',
        'export function makeKey(messageId) { return `${messageId}\\0${sideEffect()}`; }',
    ],
];

describe('fold_constants.rs', () => runCases(FOLD_CONSTANTS));
describe('dead_code_elimination.rs', () => runCases(DEAD_CODE_ELIMINATION));
